S010_002 = {
  ID = 2,
  STEP_001 = 1,
  STEP_005 = 5,
  STEP_010 = 10,
  STEP_015 = 15,
  STEP_016 = 16,
  STEP_017 = 17,
  STEP_020 = 20,
  STEP_030 = 30,
  STEP_255 = 255
}
local fldtxt = "s010_002_010"
local base = "s010_002_"
local text_file = "s010_002"
local tlk = Tlk:new(text_file, 1, true)

function S010_002:Event_010()
  local hiroko_index = GetIndex(NPC, "npc_0500")
  local fn01_01 = Motion.Object:new(NPC, "npc_0500", "fn01_01")
  Field.ObjectLoadMotion(NPC, hiroko_index, "fn01_01")
  Field.ObjectLoadMotion(NPC, hiroko_index, "e002")
  Field.ObjectLoadMotion(NPC, hiroko_index, "e004")
  Field.ObjectLoadMotion(NPC, hiroko_index, "e006")
  Field.ObjectLoadMotion(NPC, hiroko_index, "e008")
  Field.ObjectLoadMotion(NPC, hiroko_index, "e010")
  Field.ObjectLoadMotion(NPC, hiroko_index, "e012")
  Field.ObjectLoadMotion(PLAYER, 1, "e002")
  Field.ObjectLoadMotion(PLAYER, 1, "e004_01")
  Field.ObjectLoadMotion(PLAYER, 1, "e008")
  Field.ObjectLoadMotion(PLAYER, 1, "e012")
  Field.ObjectLoadMotion(PLAYER, 1, "e013")
  Field.ObjectLoadMotion(PLAYER, 1, "e015")
  Field.ObjectLoadMotion(PLAYER, 1, "e018")
  Field.ObjectLoadMotion(PLAYER, 1, "e019")
  Field.ObjectLoadExpression(NPC, hiroko_index, "F08")
  if Qst.Sub:Check(self.ID, self.STEP_001, self.STEP_005) then
    tlk:StartTalkActionAndZoom("npc_0500")
    HideMinimap(true)
    HideGuide(true)
    fn01_01:Play(10, true)
    ObjectTurnToPlayer(NPC, "npc_0500")
    WaitFrame(20)
    Field.ObjectChangeExpression(NPC, hiroko_index, "F01", EYES_BLINK_TYPE_BLINK, true, 30, AUTO_CANCEL_NONE, 15)
    Field.ObjectPlayMotion(NPC, hiroko_index, "e012", 15, true)
    tlk:Message("s010_002_010")
    Field.ObjectChangeExpression(NPC, hiroko_index, "F01", EYES_BLINK_TYPE_BLINK, false, 30, AUTO_CANCEL_NONE, 15)
    local result = tlk:Select(3, base .. "020")
    WaitFrame(15)
    Field.ObjectChangeExpression(NPC, hiroko_index, "F01", EYES_BLINK_TYPE_BLINK, true, 30, AUTO_CANCEL_NONE, 15)
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, hiroko_index, "e002", 10, 10)
    if result == RESULT_TALK00 then
      tlk:Message("s010_002_030")
    elseif result == RESULT_TALK01 then
      tlk:Message("s010_002_040")
    elseif result == RESULT_TALK02 then
      tlk:Message("s010_002_050")
    end
    Field.ObjectPlayMotion(NPC, hiroko_index, "e012", 15, true)
    tlk:Message("s010_002_060")
    tlk:Message("s010_002_070")
    Field.ObjectChangeExpression(NPC, hiroko_index, "F01", EYES_BLINK_TYPE_BLINK, false, 30, AUTO_CANCEL_NONE, 15)
    local result = tlk:Select(3, base .. "080")
    WaitFrame(15)
    Field.ObjectPlayMotion(NPC, hiroko_index, "e008", 15, true)
    Field.ObjectChangeExpression(NPC, hiroko_index, "F01", EYES_BLINK_TYPE_BLINK, true, 30, AUTO_CANCEL_NONE, 15)
    if result == RESULT_TALK00 then
      tlk:Message("s010_002_090")
    elseif result == RESULT_TALK01 then
      tlk:Message("s010_002_100")
    elseif result == RESULT_TALK02 then
      tlk:Message("s010_002_110")
    end
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, hiroko_index, "e002", 10, 10)
    tlk:Message("s010_002_120")
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, hiroko_index, "e008", 10, 10)
    tlk:Message("s010_002_130")
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, hiroko_index, "e002", 10, 10)
    tlk:Message("s010_002_140")
    Field.ObjectChangeExpression(NPC, hiroko_index, "F01", EYES_BLINK_TYPE_BLINK, false, 30, AUTO_CANCEL_NONE, 15)
    local result = tlk:Select(3, base .. "150")
    WaitFrame(15)
    if result == RESULT_TALK00 then
      Field.ObjectChangeExpression(NPC, hiroko_index, "F08", EYES_BLINK_TYPE_BLINK, true, FACE_BLENDTIME, AUTO_CANCEL_NONE, 15)
      Flg.Set("FLAG_S002_011")
      Field.ObjectPlayMotionWithStartMoveMotion(NPC, hiroko_index, "e004", 10, 10)
      tlk:Message("s010_002_160")
      Flg.Set("FLAG_S002_001")
      Field.ObjectChangeExpression(NPC, hiroko_index, "F01", EYES_BLINK_TYPE_BLINK, true, FACE_BLENDTIME, AUTO_CANCEL_NONE, 15)
      Field.ObjectPlayMotionWithStartMoveMotion(NPC, hiroko_index, "e008", 10, 10)
      tlk:Message("s010_002_230")
      Field.ObjectPlayMotionWithStartMoveMotion(NPC, hiroko_index, "e002", 10, 10)
      tlk:Message("s010_002_235")
      Field.ObjectChangeExpression(NPC, hiroko_index, "F01", EYES_BLINK_TYPE_BLINK, false, FACE_BLENDTIME, AUTO_CANCEL_NONE, 15)
      tlk:EndTalkActionAndZoom()
      Qst.Sub:Start(self.ID, 1, false)
      FadeOutWithWait(0, 15)
      Obj:new(NPC, "npc_0500"):Invisible()
      FadeInWithWait(0, 15)
      HideMinimap(false)
      HideGuide(false)
      Qst.Sub:Set(self.ID, self.STEP_005)
      Qst.Sub:Set(self.ID, self.STEP_010)
    elseif result == RESULT_TALK01 then
      Flg.Set("FLAG_S002_011")
      Field.ObjectChangeExpression(NPC, hiroko_index, "F01", EYES_BLINK_TYPE_BLINK, true, 30, AUTO_CANCEL_NONE, 15)
      tlk:Message("s010_002_170")
      Flg.Set("FLAG_S002_001")
      Field.ObjectPlayMotionWithStartMoveMotion(NPC, hiroko_index, "e008", 10, 10)
      tlk:Message("s010_002_230")
      Field.ObjectPlayMotionWithStartMoveMotion(NPC, hiroko_index, "e002", 10, 10)
      tlk:Message("s010_002_235")
      tlk:EndTalkActionAndZoom()
      Field.ObjectChangeExpression(NPC, hiroko_index, "F01", EYES_BLINK_TYPE_BLINK, false, 30, AUTO_CANCEL_NONE, 15)
      Qst.Sub:Start(self.ID, 1, false)
      FadeOutWithWait(0, 15)
      Obj:new(NPC, "npc_0500"):Invisible()
      FadeInWithWait(0, 15)
      HideMinimap(false)
      HideGuide(false)
      Qst.Sub:Set(self.ID, self.STEP_005)
      Qst.Sub:Set(self.ID, self.STEP_010)
    else
      if result == RESULT_TALK02 then
        Field.ObjectChangeExpression(NPC, hiroko_index, "F01", EYES_BLINK_TYPE_BLINK, true, 30, AUTO_CANCEL_NONE, 15)
        Field.ObjectPlayMotionWithStartMoveMotion(NPC, hiroko_index, "e012", 10, 10)
        tlk:Message("s010_002_180")
        Flg.Set("FLAG_S002_001")
        tlk:EndTalkActionAndZoom()
        HideMinimap(false)
        HideGuide(false)
        Field.ObjectChangeExpression(NPC, hiroko_index, "F01", EYES_BLINK_TYPE_BLINK, false, 30, AUTO_CANCEL_NONE, 15)
        Qst.Sub:Set(self.ID, self.STEP_005)
      else
      end
    end
  elseif Qst.Sub:Check(self.ID, self.STEP_005, self.STEP_010) then
    HideMinimap(true)
    HideGuide(true)
    fn01_01:Play(10, true)
    Obj:new(NPC, "npc_0500"):SetRotationYToPlayer(20)
    WaitFrame(20)
    tlk:StartTalkActionAndZoom("npc_0500")
    Field.ObjectChangeExpression(NPC, hiroko_index, "F01", EYES_BLINK_TYPE_BLINK, true, 30, AUTO_CANCEL_NONE, 15)
    tlk:Message("s010_002_190")
    Field.ObjectChangeExpression(NPC, hiroko_index, "F01", EYES_BLINK_TYPE_BLINK, false, 30, AUTO_CANCEL_NONE, 15)
    local result = tlk:Select(2, base .. "200")
    WaitFrame(15)
    if result == RESULT_TALK00 then
      Field.ObjectChangeExpression(NPC, hiroko_index, "F08", EYES_BLINK_TYPE_BLINK, true, FACE_BLENDTIME, AUTO_CANCEL_NONE, 15)
      Field.ObjectPlayMotionWithStartMoveMotion(NPC, hiroko_index, "e004", 10, 10)
      tlk:Message("s010_002_210")
      Flg.Set("FLAG_S002_001")
      Flg.Set("FLAG_S002_011")
      Field.ObjectChangeExpression(NPC, hiroko_index, "F01", EYES_BLINK_TYPE_BLINK, true, FACE_BLENDTIME, AUTO_CANCEL_NONE, 15)
      Field.ObjectPlayMotionWithStartMoveMotion(NPC, hiroko_index, "e008", 10, 10)
      tlk:Message("s010_002_230")
      Field.ObjectPlayMotionWithStartMoveMotion(NPC, hiroko_index, "e002", 10, 10)
      tlk:Message("s010_002_235")
      tlk:EndTalkActionAndZoom()
      Field.ObjectChangeExpression(NPC, hiroko_index, "F01", EYES_BLINK_TYPE_BLINK, false, 30, AUTO_CANCEL_NONE, 15)
      Qst.Sub:Start(self.ID, 1, false)
      FadeOutWithWait(0, 15)
      Obj:new(NPC, "npc_0500"):Invisible()
      FadeInWithWait(0, 15)
      HideMinimap(false)
      HideGuide(false)
      Qst.Sub:Set(self.ID, self.STEP_010)
    else
      Field.ObjectChangeExpression(NPC, hiroko_index, "F01", EYES_BLINK_TYPE_BLINK, true, 30, AUTO_CANCEL_NONE, 15)
      Field.ObjectPlayMotionWithStartMoveMotion(NPC, hiroko_index, "e002", 10, 10)
      tlk:Message("s010_002_220")
      tlk:EndTalkActionAndZoom()
      HideMinimap(false)
      HideGuide(false)
      Field.ObjectChangeExpression(NPC, hiroko_index, "F01", EYES_BLINK_TYPE_BLINK, false, 30, AUTO_CANCEL_NONE, 15)
    end
  end
end

function S010_002:Event_020()
  local kuroi_index = GetIndex(NPC, "npc_0500")
  local hiroko_index = GetIndex(NPC, "npc_0502")
  Field.ObjectLoadMotion(NPC, hiroko_index, "fn01_01")
  Field.ObjectLoadMotion(NPC, hiroko_index, "e002")
  Field.ObjectLoadMotion(NPC, hiroko_index, "e004")
  Field.ObjectLoadMotion(NPC, hiroko_index, "e006")
  Field.ObjectLoadMotion(NPC, hiroko_index, "e008")
  Field.ObjectLoadMotion(NPC, hiroko_index, "e010")
  Field.ObjectLoadMotion(NPC, hiroko_index, "e012")
  Field.ObjectLoadMotion(NPC, hiroko_index, "e020")
  Field.ObjectLoadMotion(NPC, kuroi_index, "fn01_01")
  Field.ObjectLoadMotion(NPC, kuroi_index, "e002")
  Field.ObjectLoadMotion(NPC, kuroi_index, "e004")
  Field.ObjectLoadMotion(NPC, kuroi_index, "e006")
  Field.ObjectLoadMotion(NPC, kuroi_index, "e008")
  Field.ObjectLoadMotion(NPC, kuroi_index, "e012")
  Field.ObjectLoadMotion(PLAYER, 1, "e002")
  Field.ObjectLoadMotion(PLAYER, 1, "e004_01")
  Field.ObjectLoadMotion(PLAYER, 1, "e008")
  Field.ObjectLoadMotion(PLAYER, 1, "e012")
  Field.ObjectLoadMotion(PLAYER, 1, "e013")
  Field.ObjectLoadMotion(PLAYER, 1, "e015")
  Field.ObjectLoadMotion(PLAYER, 1, "e018")
  Field.ObjectLoadMotion(PLAYER, 1, "e019")
  if Qst.Sub:Check(self.ID, self.STEP_010, self.STEP_015) then
    HideMinimap(true)
    HideGuide(true)
    Cam.Inst:Set(81.094, 1.285, -9.596, 71.624, 2.32, -12.635, default, 30)
    WaitFrame(30)
    tlk:StartTalkAndCancelDigimonRide()
    Field.ObjectChangeExpression(NPC, hiroko_index, "F01", EYES_BLINK_TYPE_BLINK, true, 30, AUTO_CANCEL_NONE, 15)
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, hiroko_index, "e002", 10, 10)
    tlk:Message("s010_002_240")
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, hiroko_index, "e008", 10, 10)
    tlk:Message("s010_002_250")
    Field.ObjectChangeExpression(NPC, hiroko_index, "F01", EYES_BLINK_TYPE_BLINK, false, 30, AUTO_CANCEL_NONE, 15)
    Flg.Set("FLAG_S002_009")
    BackFade_OutNoLoading(FADE_BLACK, FADE_TIME)
    WaitFrame(30)
    Field_StopBGM()
    tlk:Message("s010_002_260")
    FieldObjectSync(NPC, true)
    Cam.Inst:Set(82.682, 0.75, -9.614, 72.979, 1.35, -11.95, default, 0)
    Obj:new(PLAYER, ""):SetPos(74.95, 0, -10.63, true)
    Obj:new(PLAYER, ""):SetRotationY(60, 0)
    ObjectTurnToObject(NPC, "npc_0502", NPC, "npc_0500")
    FadeAllInWithWait(FADE_BLACK, FADE_TIME)
    Field_PlayBGM(912)
    Field.ObjectChangeExpression(NPC, hiroko_index, "F01", EYES_BLINK_TYPE_BLINK, true, 30, AUTO_CANCEL_NONE, 15)
    Field.ObjectPlayMotionWithStartMoveMotion(PLAYER, 1, "e012", 10, 10)
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, hiroko_index, "e006", 10, 10)
    tlk:Message("s010_002_270")
    Field.ObjectChangeExpression(NPC, hiroko_index, "F01", EYES_BLINK_TYPE_BLINK, false, 30, AUTO_CANCEL_NONE, 15)
    Field.ObjectChangeExpression(NPC, kuroi_index, "F01", EYES_BLINK_TYPE_BLINK, true, 30, AUTO_CANCEL_NONE, 15)
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, kuroi_index, "e012", 10, 10)
    tlk:Message("s010_002_280")
    Field.ObjectChangeExpression(NPC, kuroi_index, "F01", EYES_BLINK_TYPE_BLINK, false, 30, AUTO_CANCEL_NONE, 15)
    ObjectTurnToPlayer(NPC, "npc_0502")
    WaitFrame(30)
    PlayerLookAtObject(NPC, "npc_0502")
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, hiroko_index, "e002", 10, 10)
    Field.ObjectChangeExpression(NPC, hiroko_index, "F01", EYES_BLINK_TYPE_BLINK, true, 30, AUTO_CANCEL_NONE, 15)
    tlk:Message("s010_002_290")
    Field.ObjectChangeExpression(NPC, hiroko_index, "F01", EYES_BLINK_TYPE_BLINK, false, 30, AUTO_CANCEL_NONE, 15)
    Field.ObjectResetAim(PLAYER, 1, 30)
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, kuroi_index, "e002", 10, 10)
    Field.ObjectChangeExpression(NPC, kuroi_index, "F01", EYES_BLINK_TYPE_BLINK, true, 30, AUTO_CANCEL_NONE, 15)
    tlk:Message("s010_002_295")
    Field.ObjectChangeExpression(NPC, kuroi_index, "F01", EYES_BLINK_TYPE_BLINK, false, 30, AUTO_CANCEL_NONE, 15)
    ObjectTurnToObject(NPC, "npc_0502", NPC, "npc_0500")
    WaitFrame(30)
    Field.ObjectChangeExpression(NPC, hiroko_index, "F01", EYES_BLINK_TYPE_BLINK, true, 30, AUTO_CANCEL_NONE, 15)
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, hiroko_index, "e020", 10, 10)
    tlk:Message("s010_002_300")
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, hiroko_index, "e002", 10, 10)
    tlk:Message("s010_002_305")
    Field.ObjectChangeExpression(NPC, hiroko_index, "F01", EYES_BLINK_TYPE_BLINK, false, 30, AUTO_CANCEL_NONE, 15)
    Field.ObjectChangeExpression(NPC, kuroi_index, "F01", EYES_BLINK_TYPE_BLINK, true, 30, AUTO_CANCEL_NONE, 15)
    Field.ObjectPlayMotion(NPC, kuroi_index, "e008", 15, true)
    tlk:Message("s010_002_310")
    Field.ObjectChangeExpression(NPC, kuroi_index, "F01", EYES_BLINK_TYPE_BLINK, false, 30, AUTO_CANCEL_NONE, 15)
    Field.ObjectChangeExpression(NPC, hiroko_index, "F01", EYES_BLINK_TYPE_BLINK, true, 30, AUTO_CANCEL_NONE, 15)
    Field.ObjectPlayMotion(NPC, hiroko_index, "e008", 15, true)
    tlk:Message("s010_002_320")
    Field.ObjectChangeExpression(NPC, hiroko_index, "F01", EYES_BLINK_TYPE_BLINK, false, 30, AUTO_CANCEL_NONE, 15)
    Field.ObjectChangeExpression(NPC, kuroi_index, "F01", EYES_BLINK_TYPE_BLINK, true, 30, AUTO_CANCEL_NONE, 15)
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, kuroi_index, "e002", 10, 10)
    tlk:Message("s010_002_330")
    Field.ObjectChangeExpression(NPC, kuroi_index, "F01", EYES_BLINK_TYPE_BLINK, false, 30, AUTO_CANCEL_NONE, 15)
    Field.ObjectChangeExpression(NPC, hiroko_index, "F01", EYES_BLINK_TYPE_BLINK, true, 30, AUTO_CANCEL_NONE, 15)
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, hiroko_index, "e002", 10, 10)
    tlk:Message("s010_002_340")
    Field.ObjectChangeExpression(NPC, hiroko_index, "F01", EYES_BLINK_TYPE_BLINK, false, 30, AUTO_CANCEL_NONE, 15)
    Field.ObjectChangeExpression(NPC, kuroi_index, "F01", EYES_BLINK_TYPE_BLINK, true, 30, AUTO_CANCEL_NONE, 15)
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, kuroi_index, "e012", 10, 10)
    tlk:Message("s010_002_350")
    Field.ObjectChangeExpression(NPC, kuroi_index, "F01", EYES_BLINK_TYPE_BLINK, false, 30, AUTO_CANCEL_NONE, 15)
    Field.ObjectChangeExpression(NPC, hiroko_index, "F01", EYES_BLINK_TYPE_BLINK, true, 30, AUTO_CANCEL_NONE, 15)
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, hiroko_index, "e008", 10, 10)
    tlk:Message("s010_002_360")
    Field.ObjectChangeExpression(NPC, hiroko_index, "F01", EYES_BLINK_TYPE_BLINK, false, 30, AUTO_CANCEL_NONE, 15)
    Field.ObjectChangeExpression(NPC, kuroi_index, "F01", EYES_BLINK_TYPE_BLINK, true, 30, AUTO_CANCEL_NONE, 15)
    Field.ObjectPlayMotion(NPC, kuroi_index, "e008", 15, true)
    tlk:Message("s010_002_365")
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, kuroi_index, "e002", 10, 10)
    tlk:Message("s010_002_370")
    Field.ObjectChangeExpression(NPC, kuroi_index, "F01", EYES_BLINK_TYPE_BLINK, false, 30, AUTO_CANCEL_NONE, 15)
    Cam.Inst:Clear(30)
    WaitFrame(30)
    Flg.Set("FLAG_S002_007")
    Flg.Set("FLAG_S002_005")
    FadeOutWithWait(0, 15)
    tlk:EndTalk()
    FieldObjectSync(FOR_ALL, false)
    Obj:new(NPC, "npc_0502"):Invisible()
    FadeInWithWait(0, 15)
    HideMinimap(false)
    HideGuide(false)
    Qst.Sub:Set(self.ID, self.STEP_015)
  elseif Qst.Sub:Check(self.ID, self.STEP_015) and not Flg.Check("FLAG_S002_008") then
    tlk:StartTalkAndCancelDigimonRide()
    START_TALK_ACTION_AND_ZOOM("npc_0500", false, true)
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, kuroi_index, "e002", 10, 10)
    Field.ObjectChangeExpression(NPC, kuroi_index, "F01", EYES_BLINK_TYPE_BLINK, true, 30, AUTO_CANCEL_NONE, 15)
    tlk:Message("s010_002_375")
    tlk:EndTalk()
    Field.ObjectChangeExpression(NPC, kuroi_index, "F01", EYES_BLINK_TYPE_BLINK, false, 30, AUTO_CANCEL_NONE, 15)
    END_TALK_ACTION_AND_ZOOM("npc_0500", false, true)
  end
end

function S010_002:Event_030()
  if Qst.Sub:Check(self.ID, self.STEP_015, self.STEP_020) then
    HideMinimap(true)
    HideGuide(true)
    if not Flg.Check("FLAG_S002_004") then
      tlk:StartTalkAndCancelDigimonRide()
      tlk:Message("s010_002_380")
      tlk:Message("s010_002_390")
      tlk:Message("s010_002_400")
      tlk:EndTalk()
    else
      tlk:StartTalkAndCancelDigimonRide()
      tlk:Message("s010_002_410")
      tlk:Message("s010_002_420")
      tlk:Message("s010_002_430")
      tlk:EndTalk()
      Flg.Set("FLAG_S002_008")
    end
    local obj1 = Obj:new(FLD_OBJ_LOCATOR, "obj_2000")
    obj1:Invisible(10)
    Flg.Set("FLAG_S002_003")
    HideMinimap(false)
    HideGuide(false)
    Qst.Sub:Set(self.ID, self.STEP_016)
  end
end

function S010_002:Event_040()
  if Qst.Sub:Check(self.ID, self.STEP_015, self.STEP_020) then
    HideMinimap(true)
    HideGuide(true)
    if not Flg.Check("FLAG_S002_003") then
      tlk:StartTalkAndCancelDigimonRide()
      tlk:Message("s010_002_380")
      tlk:Message("s010_002_390")
      tlk:Message("s010_002_400")
      tlk:EndTalk()
    else
      tlk:StartTalkAndCancelDigimonRide()
      tlk:Message("s010_002_410")
      tlk:Message("s010_002_420")
      tlk:Message("s010_002_430")
      tlk:EndTalk()
      Flg.Set("FLAG_S002_008")
    end
    local obj2 = Obj:new(FLD_OBJ_LOCATOR, "obj_2001")
    obj2:Invisible(10)
    Flg.Set("FLAG_S002_004")
    HideMinimap(false)
    HideGuide(false)
    Qst.Sub:Set(self.ID, self.STEP_017)
  end
end

function S010_002:Event_050()
  if Qst.Sub:Check(self.ID, self.STEP_016) and Qst.Sub:Check(self.ID, self.STEP_017) and not Flg.Check("FLAG_S002_002") then
    local kuroi_index = GetIndex(NPC, "npc_0500")
    local hiroko_index = GetIndex(NPC, "npc_0503")
    local toy_index = GetIndex(NPC, "npc_0501")
    Field.ObjectLoadMotion(NPC, hiroko_index, "fn01_01")
    Field.ObjectLoadMotion(NPC, hiroko_index, "e002")
    Field.ObjectLoadMotion(NPC, hiroko_index, "e004")
    Field.ObjectLoadMotion(NPC, hiroko_index, "e006")
    Field.ObjectLoadMotion(NPC, hiroko_index, "e008")
    Field.ObjectLoadMotion(NPC, hiroko_index, "e010")
    Field.ObjectLoadMotion(NPC, hiroko_index, "e012")
    Field.ObjectLoadMotion(NPC, hiroko_index, "e018")
    Field.ObjectLoadMotion(NPC, hiroko_index, "e020")
    Field.ObjectLoadMotion(NPC, kuroi_index, "fn01_01")
    Field.ObjectLoadMotion(NPC, kuroi_index, "e002")
    Field.ObjectLoadMotion(NPC, kuroi_index, "e004")
    Field.ObjectLoadMotion(NPC, kuroi_index, "e006")
    Field.ObjectLoadMotion(NPC, kuroi_index, "e007")
    Field.ObjectLoadMotion(NPC, kuroi_index, "e008")
    Field.ObjectLoadMotion(NPC, kuroi_index, "e012")
    Field.ObjectLoadMotion(NPC, kuroi_index, "e018")
    Field.ObjectLoadMotion(NPC, toy_index, "bn01")
    Field.ObjectLoadMotion(NPC, toy_index, "bd02")
    Field.ObjectLoadMotion(NPC, toy_index, "bd03")
    Field.ObjectLoadMotion(NPC, toy_index, "fe04")
    Field.ObjectLoadMotion(NPC, toy_index, "fq02")
    Field.ObjectLoadMotion(PLAYER, 1, "e002")
    Field.ObjectLoadMotion(PLAYER, 1, "e004_01")
    Field.ObjectLoadMotion(PLAYER, 1, "e008")
    Field.ObjectLoadMotion(PLAYER, 1, "e012")
    Field.ObjectLoadMotion(PLAYER, 1, "e013")
    Field.ObjectLoadMotion(PLAYER, 1, "e015")
    Field.ObjectLoadMotion(PLAYER, 1, "e018")
    Field.ObjectLoadMotion(PLAYER, 1, "e019")
    FadeOutWithWait(0, 15)
    HideMinimap(true)
    HideGuide(true)
    Cam.Inst:Set(83.046, -0.299, -9.7, 73.27, 1.61, -10.645, default, 0)
    tlk:StartTalkAndCancelDigimonRide()
    Flg.Set("FLAG_S002_010")
    Obj:new(PLAYER, ""):SetPos(75.7, 0, -10.96, true)
    Obj:new(PLAYER, ""):SetRotationY(120, 0)
    FieldObjectSync(NPC, false)
    WaitFrame(15)
    FadeInWithWait(0, 15)
    Flg.Set("FLAG_S002_002")
    Field.ObjectChangeExpression(NPC, kuroi_index, "F01", EYES_BLINK_TYPE_BLINK, true, 30, AUTO_CANCEL_NONE, 15)
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, kuroi_index, "e002", 10, 10)
    PlayerLookAtObject(NPC, "npc_0500")
    tlk:Message("s010_002_440")
    Field.ObjectChangeExpression(NPC, kuroi_index, "F01", EYES_BLINK_TYPE_BLINK, false, 30, AUTO_CANCEL_NONE, 15)
    Field.ObjectChangeExpression(NPC, hiroko_index, "F01", EYES_BLINK_TYPE_BLINK, true, 30, AUTO_CANCEL_NONE, 15)
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, hiroko_index, "e012", 10, 10)
    tlk:Message("s010_002_450")
    Field.ObjectChangeExpression(NPC, hiroko_index, "F01", EYES_BLINK_TYPE_BLINK, false, 30, AUTO_CANCEL_NONE, 15)
    Field.ObjectChangeExpression(NPC, kuroi_index, "F01", EYES_BLINK_TYPE_BLINK, true, 30, AUTO_CANCEL_NONE, 15)
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, kuroi_index, "e008", 10, 10)
    tlk:Message("s010_002_460")
    Field.ObjectChangeExpression(NPC, kuroi_index, "F01", EYES_BLINK_TYPE_BLINK, false, 30, AUTO_CANCEL_NONE, 15)
    Field.ObjectChangeExpression(NPC, hiroko_index, "F01", EYES_BLINK_TYPE_BLINK, true, 30, AUTO_CANCEL_NONE, 15)
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, hiroko_index, "e008", 10, 10)
    tlk:Message("s010_002_470")
    tlk:Message("s010_002_472")
    tlk:Message("s010_002_474")
    Field.ObjectChangeExpression(NPC, hiroko_index, "F01", EYES_BLINK_TYPE_BLINK, false, 30, AUTO_CANCEL_NONE, 15)
    Obj:new(NPC, "npc_0500"):SetRotationY(120, 15)
    Field.ObjectPlayMotion(NPC, kuroi_index, "e018", 15, true)
    SetControlScriptExternalVariable("toy_state", "start_move")
    Field.ObjectChangeExpression(NPC, kuroi_index, "F01", EYES_BLINK_TYPE_BLINK, true, 30, AUTO_CANCEL_NONE, 15)
    tlk:Message("s010_002_480")
    Field.ObjectChangeExpression(NPC, kuroi_index, "F01", EYES_BLINK_TYPE_BLINK, false, 30, AUTO_CANCEL_NONE, 15)
    PlayerObjectResetAim()
    Obj:new(NPC, "npc_0503"):SetRotationY(120, 15)
    Obj:new(PLAYER, ""):SetRotationY(120, 15)
    Field.ObjectPlayMotion(PLAYER, 1, "e018", 15, true)
    Cam.Inst:Set(81.094, 1.285, -9.596, 71.624, 2.32, -12.635, default, 30)
    Field_StopBGM()
    Field.ObjectChangeExpression(NPC, hiroko_index, "F01", EYES_BLINK_TYPE_BLINK, true, 30, AUTO_CANCEL_NONE, 15)
    Field.ObjectPlayMotion(NPC, hiroko_index, "e006", 15, true)
    tlk:Message("s010_002_490")
    local slot_id = PlaySE(405001, 100)
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, toy_index, "bd03", 10, 10)
    WaitFrame(60)
    StopSE(slot_id, 15)
    PlaySE(403001, 50)
    WaitFrame(15)
    Sound.PlayBGM(805, 0)
    tlk:Message("s010_002_500")
    Field.ObjectChangeExpression(NPC, hiroko_index, "F01", EYES_BLINK_TYPE_BLINK, false, 30, AUTO_CANCEL_NONE, 15)
    SetControlScriptExternalVariable("toy_state", "Initialize")
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, toy_index, "fq02", 10, 10)
    tlk:Message("s010_002_510")
    Field.ObjectPlayMotion(NPC, hiroko_index, "e018", 15, true)
    Field.ObjectChangeExpression(NPC, hiroko_index, "F01", EYES_BLINK_TYPE_BLINK, true, 30, AUTO_CANCEL_NONE, 15)
    tlk:Message("s010_002_520")
    Field.ObjectPlayMotion(NPC, hiroko_index, "e004", 15, true)
    tlk:Message("s010_002_530")
    Field.ObjectChangeExpression(NPC, hiroko_index, "F01", EYES_BLINK_TYPE_BLINK, false, 30, AUTO_CANCEL_NONE, 15)
    Field.ObjectChangeExpression(NPC, kuroi_index, "F01", EYES_BLINK_TYPE_BLINK, true, 30, AUTO_CANCEL_NONE, 15)
    tlk:Message("s010_002_540")
    Field.ObjectChangeExpression(NPC, kuroi_index, "F01", EYES_BLINK_TYPE_BLINK, false, 30, AUTO_CANCEL_NONE, 15)
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, toy_index, "fq02", 10, 10)
    tlk:Message("s010_002_550")
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, toy_index, "fe04", 10, 10)
    tlk:Message("s010_002_560")
    tlk:EndTalk(true)
    Qst.Sub:Set(self.ID, self.STEP_020)
    EncountFromField_WithNormalEffect(20100020, 271, false)
  end
end

function S010_002:Event_060()
  if Qst.Sub:Check(self.ID, self.STEP_020, self.STEP_030) and Flg.Check("FLAG_S002_000") then
    local kuroi_index = GetIndex(NPC, "npc_0500")
    local hiroko_index = GetIndex(NPC, "npc_0503")
    Field.ObjectLoadMotion(NPC, hiroko_index, "fn01_01")
    Field.ObjectLoadMotion(NPC, hiroko_index, "e002")
    Field.ObjectLoadMotion(NPC, hiroko_index, "e004")
    Field.ObjectLoadMotion(NPC, hiroko_index, "e006")
    Field.ObjectLoadMotion(NPC, hiroko_index, "e008")
    Field.ObjectLoadMotion(NPC, hiroko_index, "e010")
    Field.ObjectLoadMotion(NPC, hiroko_index, "e012")
    Field.ObjectLoadMotion(NPC, hiroko_index, "e018")
    Field.ObjectLoadMotion(NPC, hiroko_index, "e020")
    Field.ObjectLoadMotion(NPC, kuroi_index, "fn01_01")
    Field.ObjectLoadMotion(NPC, kuroi_index, "e002")
    Field.ObjectLoadMotion(NPC, kuroi_index, "e004")
    Field.ObjectLoadMotion(NPC, kuroi_index, "e006")
    Field.ObjectLoadMotion(NPC, kuroi_index, "e007")
    Field.ObjectLoadMotion(NPC, kuroi_index, "e008")
    Field.ObjectLoadMotion(NPC, kuroi_index, "e012")
    Field.ObjectLoadMotion(NPC, kuroi_index, "e018")
    Field.ObjectLoadMotion(PLAYER, 1, "e002")
    Field.ObjectLoadMotion(PLAYER, 1, "e004_01")
    Field.ObjectLoadMotion(PLAYER, 1, "e008")
    Field.ObjectLoadMotion(PLAYER, 1, "e012")
    Field.ObjectLoadMotion(PLAYER, 1, "e013")
    Field.ObjectLoadMotion(PLAYER, 1, "e015")
    Field.ObjectLoadMotion(PLAYER, 1, "e018")
    Field.ObjectLoadMotion(PLAYER, 1, "e019")
    local toy_index = GetIndex(NPC, "npc_0501")
    HideMinimap(true)
    HideGuide(true)
    tlk:StartTalkAndCancelDigimonRide()
    FadeAllInWithWait(FADE_BLACK, FADE_TIME)
    Field.ObjectPlayMotion(NPC, toy_index, "bd02", 15, false)
    PlaySE(300201, 100)
    WaitFrame(30)
    PlaySE(200006, 100)
    FieldObjectSync(NPC, true)
    WaitFrame(30)
    Sound.PlayBGM(912, 0)
    Field.ObjectPlayMotion(NPC, hiroko_index, "e008", 15, true)
    Field.ObjectPlayMotion(PLAYER, 1, "fn01_01", 15, true)
    Field.ObjectChangeExpression(NPC, hiroko_index, "F01", EYES_BLINK_TYPE_BLINK, true, 30, AUTO_CANCEL_NONE, 15)
    tlk:Message("s010_002_570")
    Field.ObjectChangeExpression(NPC, hiroko_index, "F01", EYES_BLINK_TYPE_BLINK, false, 30, AUTO_CANCEL_NONE, 15)
    Cam.Inst:Set(82.7, -0.55, -9.301, 73.15, 1.434, -11.523, default, 30)
    WaitFrame(15)
    Field.ObjectPlayMotion(NPC, kuroi_index, "e008", 15, true)
    Field.ObjectChangeExpression(NPC, kuroi_index, "F01", EYES_BLINK_TYPE_BLINK, true, 30, AUTO_CANCEL_NONE, 15)
    tlk:Message("s010_002_580")
    tlk:Message("s010_002_590")
    Field.ObjectChangeExpression(NPC, kuroi_index, "F01", EYES_BLINK_TYPE_BLINK, false, 30, AUTO_CANCEL_NONE, 15)
    ObjectTurnToObject(NPC, "npc_0503", NPC, "npc_0500")
    PlayerLookAtObject(NPC, "npc_0500")
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, hiroko_index, "e002", 10, 10)
    Field.ObjectChangeExpression(NPC, hiroko_index, "F01", EYES_BLINK_TYPE_BLINK, true, 30, AUTO_CANCEL_NONE, 15)
    tlk:Message("s010_002_600")
    Field.ObjectChangeExpression(NPC, hiroko_index, "F01", EYES_BLINK_TYPE_BLINK, false, 30, AUTO_CANCEL_NONE, 15)
    Field.ObjectLookAtTheObject(NPC, kuroi_index, PLAYER, 1, 30)
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, kuroi_index, "e002", 10, 10)
    Field.ObjectChangeExpression(NPC, kuroi_index, "F01", EYES_BLINK_TYPE_BLINK, true, 30, AUTO_CANCEL_NONE, 15)
    tlk:Message("s010_002_610")
    tlk:Message("s010_002_620")
    Field.ObjectChangeExpression(NPC, kuroi_index, "F01", EYES_BLINK_TYPE_BLINK, false, 30, AUTO_CANCEL_NONE, 15)
    tlk:EndTalk(true)
    Qst.Sub:Set(self.ID, self.STEP_030)
    Flg.Set("FLAG_SKIP_AREACHANGE_MOVE")
    MapChange("t", 201, "start_00", true, 0, FADE_TIME)
  end
end

function S010_002:Event_070()
  if Qst.Sub:Check(self.ID, self.STEP_030, self.STEP_255) and Flg.Check("FLAG_S002_000") then
    local hiroko_index = GetIndex(NPC, "s010_002_hiroko")
    Field.ObjectLoadMotion(NPC, hiroko_index, "fn01_01")
    Field.ObjectLoadMotion(NPC, hiroko_index, "e002")
    Field.ObjectLoadMotion(NPC, hiroko_index, "e004")
    Field.ObjectLoadMotion(NPC, hiroko_index, "e006")
    Field.ObjectLoadMotion(NPC, hiroko_index, "e008")
    Field.ObjectLoadMotion(NPC, hiroko_index, "e010")
    Field.ObjectLoadMotion(NPC, hiroko_index, "e012")
    Field.ObjectLoadMotion(NPC, hiroko_index, "e018")
    Field.ObjectLoadMotion(NPC, hiroko_index, "e020")
    Field.ObjectLoadMotion(PLAYER, 1, "e002")
    Field.ObjectLoadMotion(PLAYER, 1, "e004_01")
    Field.ObjectLoadMotion(PLAYER, 1, "e008")
    Field.ObjectLoadMotion(PLAYER, 1, "e012")
    Field.ObjectLoadMotion(PLAYER, 1, "e013")
    Field.ObjectLoadMotion(PLAYER, 1, "e015")
    Field.ObjectLoadMotion(PLAYER, 1, "e018")
    Field.ObjectLoadMotion(PLAYER, 1, "e019")
    HideMinimap(true)
    HideGuide(true)
    Cam.Inst:Set(12.07, 0.40436, 34.962, 8.9939, 1.61975, 44.4, default, 0)
    Field.SetMobTransparentFrontOfCamera(0, 10, 10, 10)
    Field.ObjectLookAtTheObject(NPC, hiroko_index, PLAYER, 1, 30)
    Obj:new(PLAYER, ""):SetRotationY(-30, 0)
    PlayerLookAtObject(NPC, "s010_002_hiroko")
    tlk:StartTalkAndCancelDigimonRide()
    FadeAllInWithWait(FADE_BLACK, FADE_TIME)
    Field.ObjectChangeExpression(NPC, hiroko_index, "F01", EYES_BLINK_TYPE_BLINK, true, 30, AUTO_CANCEL_NONE, 15)
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, hiroko_index, "e010", 10, 10)
    tlk:Message("s010_002_640")
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, hiroko_index, "e002", 10, 10)
    tlk:Message("s010_002_650")
    tlk:Message("s010_002_660")
    Field.ObjectChangeExpression(NPC, hiroko_index, "F01", EYES_BLINK_TYPE_BLINK, false, 30, AUTO_CANCEL_NONE, 15)
    local result = tlk:Select(3, base .. "670")
    WaitFrame(15)
    Field.ObjectChangeExpression(NPC, hiroko_index, "F01", EYES_BLINK_TYPE_BLINK, true, 30, AUTO_CANCEL_NONE, 15)
    Field.ObjectPlayMotion(NPC, hiroko_index, "e008", 15, true)
    if result == RESULT_TALK00 then
      tlk:Message("s010_002_680")
    elseif result == RESULT_TALK01 then
      tlk:Message("s010_002_690")
    elseif result == RESULT_TALK02 then
      tlk:Message("s010_002_700")
    end
    tlk:Message("s010_002_710")
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, hiroko_index, "e002", 10, 10)
    tlk:Message("s010_002_720")
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, hiroko_index, "e012", 10, 10)
    tlk:Message("s010_002_730")
    Field.ObjectChangeExpression(NPC, hiroko_index, "F01", EYES_BLINK_TYPE_BLINK, false, 30, AUTO_CANCEL_NONE, 15)
    Flg.Set("FLAG_IS_CLEAR_S010_002")
    FadeOutWithWait(0, 15)
    Obj:new(NPC, "s010_002_hiroko"):Invisible()
    tlk:EndTalk()
    FadeInWithWait(0, 15)
    Cam.Inst:Clear(30)
    Field.ClearMobTransparentFrontOfCamera(0)
    HideMinimap(false)
    HideGuide(false)
    Qst.Sub:End(self.ID, self.STEP_255)
  end
end
