gGimText = "field_text"

function Prcs_d1301_OpenDoor(obj_id, cl_name, gim_name)
  Obj:new(ENEMY, "enemysecurity_01"):Invisible(15)
  Obj:new(ENEMY, "enemysecurity_02"):Invisible(15)
  Obj:new(ENEMY, "enemysecurity_03"):Invisible(15)
  Obj:new(ENEMY, "enemysecurity_04"):Invisible(15)
  Obj:new(ENEMY, "enemy_001"):Invisible(15)
  Obj:new(ENEMY, "enemy_002"):Invisible(15)
  Obj:new(ENEMY, "enemy_003"):Invisible(15)
  Obj:new(ENEMY, "enemy_004"):Invisible(15)
  Obj:new(ENEMY, "enemy_005"):Invisible(15)
  Obj:new(ENEMY, "enemy_006"):Invisible(15)
  Obj:new(ENEMY, "enemy_007"):Invisible(15)
  Obj:new(ENEMY, "enemy_008"):Invisible(15)
  Obj:new(ENEMY, "enemy_008"):Invisible(15)
  Obj:new(ENEMY, "enemy_010"):Invisible(15)
  Obj:new(ENEMY, "enemy_011"):Invisible(15)
  Obj:new(ENEMY, "enemy_012"):Invisible(15)
  PlayerTurnToObject(FLD_OBJ_GIMMICK, gim_name, true, false, 0, 0)
  Motion.Player:Play("fg07_m01", 0, false)
  WaitFrame(15)
  PlaySE(200025, 100)
  WaitFrame(15)
  Motion.Gimmick:Play(obj_id, "e001", false)
  PlaySE(200024, 50)
  WaitFrame(60)
  Obj:new(ENEMY, "enemysecurity_01"):CancelInvisible(15)
  Obj:new(ENEMY, "enemysecurity_02"):CancelInvisible(15)
  Obj:new(ENEMY, "enemysecurity_03"):CancelInvisible(15)
  Obj:new(ENEMY, "enemysecurity_04"):CancelInvisible(15)
  Obj:new(ENEMY, "enemy_001"):CancelInvisible(15)
  Obj:new(ENEMY, "enemy_002"):CancelInvisible(15)
  Obj:new(ENEMY, "enemy_003"):CancelInvisible(15)
  Obj:new(ENEMY, "enemy_004"):CancelInvisible(15)
  Obj:new(ENEMY, "enemy_005"):CancelInvisible(15)
  Obj:new(ENEMY, "enemy_006"):CancelInvisible(15)
  Obj:new(ENEMY, "enemy_007"):CancelInvisible(15)
  Obj:new(ENEMY, "enemy_008"):CancelInvisible(15)
  Obj:new(ENEMY, "enemy_008"):CancelInvisible(15)
  Obj:new(ENEMY, "enemy_010"):CancelInvisible(15)
  Obj:new(ENEMY, "enemy_011"):CancelInvisible(15)
  Obj:new(ENEMY, "enemy_012"):CancelInvisible(15)
end

function Prcs_d1301_EnterElv()
  Field_InvisibleFollowerAllPartyMember(0, 10, false)
  Field_InvisibleFollowerAllGuest(0, 10, false)
  Field_InvisibleFollowerAllPartyMember(INVISIBLE_KEY_FIELD, 0, false)
  Cam.Inst:Set(33.09, 1.07, 4.7, 27.17, 2.29, 5.98, default, 30)
  WaitFrame(10)
  Motion.Gimmick:Play("change_0001", "e001", false)
  PlaySE(200013, 100)
  WaitFrame(60)
  PlayerObjectResetAim()
  ColOff("wall_cl_9001")
  Field.AdjustSpeedMovePlayerToTargetFrame2D(37.5, 5, 30)
  WaitFrame(30)
  Motion.Gimmick:Play("change_0001", "e002", false)
  PlaySE(200011, 100)
  Motion.Gimmick:WaitFrame("change_0001", "e002", 0)
  local slot_num = Sound.PlaySE(200012, 100)
  Work.Set(99, slot_num)
  WaitFrame(30)
  MapChange("d", 1304, "start_01", true, 0, 15)
end

function Prcs_d1301_ExitElv()
  local slot_num = Work.Get(99)
  Field_InvisibleFollowerAllPartyMember(0, 0, false)
  Field_InvisibleFollowerAllGuest(0, 0, false)
  Cam.Inst:Set(36.23, 0.12, 3.78, 26.68, 2.8, 6.48, default, 0)
  SetFollowerCameraOperateRotation(20, 90)
  if Guest.IsExist(GST_SIMONS) then
    local pc = Obj:new(PLAYER, "")
    Obj:new(NPC, "npc_0032"):CancelInvisible()
    Obj:new(NPC, "npc_0033"):CancelInvisible()
    Obj:new(NPC, "npc_0034"):CancelInvisible()
    Obj:new(FLD_OBJ_FOLLOWER, GST_SIMONS, "guest"):SetRotationY(pc.rot_y, 0)
    Obj:new(FLD_OBJ_FOLLOWER, GST_ASUKA_B, "guest"):SetRotationY(pc.rot_y, 0)
    Obj:new(FLD_OBJ_FOLLOWER, GST_BEELSTARMON, "guest"):SetRotationY(pc.rot_y, 0)
  end
  Fade.In(0, Util.SecondFromFrame(30))
  Sound.StopSE(slot_num, 0)
  Motion.Gimmick:Play("change_0001", "e001", false)
  WaitFrame(15)
  PlaySE(200013, 100)
  ColOff("wall_cl_9001")
  WaitFrame(45)
  if Guest.IsExist(GST_SIMONS) then
    Fade_OutNoLoadingWithWait(FADE_BLACK, FADE_TIME)
    Obj:new(PLAYER, ""):SetPos(31.5, 0, 5, true)
    Obj:new(NPC, "npc_0032"):Invisible()
    Obj:new(NPC, "npc_0033"):Invisible()
    Obj:new(NPC, "npc_0034"):Invisible()
    Obj:new(FLD_OBJ_FOLLOWER, GST_SIMONS, "guest"):SetPos(31.15, 0, 3.419, true)
    Obj:new(FLD_OBJ_FOLLOWER, GST_ASUKA_B, "guest"):SetPos(31.119, 0, 6.57, true)
    Obj:new(FLD_OBJ_FOLLOWER, GST_BEELSTARMON, "guest"):SetPos(33.877, 0, 5.092, true)
  else
    Field.AdjustSpeedMovePlayerToTargetFrame2D(31.3, 5, 30)
  end
  WaitFrame(30)
  Motion.Gimmick:Play("change_0001", "e002", false)
  PlaySE(200011, 100)
  Motion.Gimmick:WaitFrame("change_0001", "e002", 0)
  local rot = Field.ObjectGetRotationTargetY(PLAYER, 1)
  SetFollowerCameraOperateRotation(0, rot + 270)
  Cam.Inst:Clear(30)
  Field_CancelInvisibleFollowerAllPartyMember(INVISIBLE_KEY_FIELD, 30, false, false)
  ColOn("wall_cl_9001")
  WaitFrame(30)
  Field_CancelInvisibleFollowerAllPartyMember(0, 30, false, true)
  Field_CancelInvisibleFollowerAllGuest(0, 30, false, true)
end

function Prcs_d1301_SwitchingGimmickAccess(array, is_access)
  local gim_name, tag
  for num = 1, #array do
    gim_name = array[num]
    tag = Field.ObjectGetTag(FLD_OBJ_GIMMICK, GetIndex(FLD_OBJ_GIMMICK, gim_name))
    if is_access == false then
      Field.ObjectSetEnableCheckAndFieldAttack(FLD_OBJ_GIMMICK, GetIndex(FLD_OBJ_GIMMICK, gim_name), is_access)
    elseif tag == "pc" then
      Field.ObjectSetEnableCheckAndFieldAttack(FLD_OBJ_GIMMICK, GetIndex(FLD_OBJ_GIMMICK, gim_name), is_access)
    elseif tag == "whiteboard" then
      if Flg.Check("FLAG_GIMMICK_D13_080") then
        Field.ObjectSetEnableCheckAndFieldAttack(FLD_OBJ_GIMMICK, GetIndex(FLD_OBJ_GIMMICK, gim_name), is_access)
      else
        Field.ObjectSetEnableCheckAndFieldAttack(FLD_OBJ_GIMMICK, GetIndex(FLD_OBJ_GIMMICK, gim_name), false)
      end
    elseif tag == "rack" then
      if Flg.Check("FLAG_GIMMICK_D13_090") then
        Field.ObjectSetEnableCheckAndFieldAttack(FLD_OBJ_GIMMICK, GetIndex(FLD_OBJ_GIMMICK, gim_name), is_access)
      else
        Field.ObjectSetEnableCheckAndFieldAttack(FLD_OBJ_GIMMICK, GetIndex(FLD_OBJ_GIMMICK, gim_name), false)
      end
    else
      Field.ObjectSetEnableCheckAndFieldAttack(FLD_OBJ_GIMMICK, GetIndex(FLD_OBJ_GIMMICK, gim_name), is_access)
    end
  end
end

function Prcs_d1301_ClosedDoor(id)
  if id == 1 then
    local tlk = Tlk:new("d13", 1, true)
    tlk:StartTalk()
    tlk:Message("f_d1301_0350_0010")
    tlk:EndTalk()
  elseif id == 2 then
    local tlk = Tlk:new("d13", 1, true)
    tlk:StartTalk()
    tlk:Message("f_d1301_0340_0010")
    tlk:EndTalk()
  end
end

function Prcs_d1301_FA_DefeatedEbamon()
  Flg.Set("FLAG_GIMMICK_D13_110")
  Flg.Set("FLAG_GIMMICK_D13_120")
  FieldObjectSync(OGIM, false)
  local tlk = Tlk:new("d13", 1, true)
  tlk:StartTalk()
  WaitFrame(20)
  INFO_GET_ITEM(793, 1)
  WaitFrame(20)
  AnswerTheCall()
  tlk:Message("f_d1301_0320_0010")
  tlk:Message("f_d1301_0320_0020")
  tlk:EndTalk()
  EndTheCall()
  Flg.Set("FLAG_MAIN_17_038")
  Qst.Main:Set(M390.ID, M390.STEP_055)
end

function Prcs_d1302_OpenDoor(obj_id, cl_name, gim_name)
  PlayerTurnToObject(FLD_OBJ_GIMMICK, gim_name, true, false, 0, 0)
  Motion.Player:Play("fg07_m01", 0, false)
  WaitFrame(15)
  PlaySE(200025, 100)
  WaitFrame(15)
  Motion.Gimmick:Play(obj_id, "e001", false)
  PlaySE(200024, 50)
  WaitFrame(60)
end

function Prcs_d1302_OpenShutter()
  Field.ObjectLoadMotion(OGIM, GetIndex(OGIM, "elv_shutter_01"), "e001")
  Flg.Set("FLAG_GIMMICK_D13_220")
  PlayerTurnToObject(FLD_OBJ_GIMMICK, "elv_open_access", true, false, 0, 0)
  Motion.Player:Play("fg07_m01", 0, false)
  WaitFrame(15)
  PlaySE(200025, 100)
  WaitFrame(15)
  Field.ObjectPlayMotion(OGIM, GetIndex(OGIM, "elv_shutter_01"), "e001", 10, false)
  PlaySE(200024, 50)
  SetControlScriptExternalVariable("shutter_se", "start")
  Obj:new(FLD_OBJ_GIMMICK, "elv_shutter_col"):Invisible()
  Obj:new(FLD_OBJ_GIMMICK, "elv_open_access"):Invisible()
  Obj:new(FLD_OBJ_GIMMICK, "elv_open_access"):SetEnableGimmick(false)
  Obj:new(FLD_OBJ_GIMMICK, "elv_access"):CancelInvisible()
  Obj:new(FLD_OBJ_GIMMICK, "elv_access"):SetEnableGimmick(true)
  WaitFrame(60)
end

function Prcs_d1302_OpenShutter_Evt()
  Field.ObjectLoadMotion(OGIM, GetIndex(OGIM, "elv_shutter_01"), "e001")
  Flg.Set("FLAG_GIMMICK_D13_220")
  PlayerTurnToObject(FLD_OBJ_GIMMICK, "elv_open_access", true, false, 0, 0)
  Motion.Player:Play("fg07_m01", 0, false)
  WaitFrame(30)
end

function Prcs_d1302_CloseShutter()
  Flg.Clear("FLAG_GIMMICK_D13_220")
  Field.ObjectLoadMotion(OGIM, GetIndex(OGIM, "elv_shutter_01"), "e002")
  PlayerTurnToObject(FLD_OBJ_GIMMICK, "elv_access", true, false, 0, 0)
  Motion.Player:Play("fg07_m01", 0, false)
  WaitFrame(15)
  PlaySE(200025, 100)
  WaitFrame(15)
end

function Prcs_d1304_DuctStart()
  FadeOutWithWait(0, 30)
  SetProhibitDigimonRide(true)
  Field_InvisibleFollowerAllPartyMember(0, 0, false)
  Motion.Player:ChangeMoveAnim("hide", 1.5)
  SetPlayerLocator("duct_0001")
  FadeInWithWait(0, 30)
end

function Prcs_d1304_DuctEnd()
  FadeOutWithWait(0, 30)
  CameraSwitchChange("followcam_default_loc", true)
  Motion.Player:ResetMoveAnim()
  SetPlayerLocator("duct_0002")
  SetFollowerCameraOperateRotation(10, 0)
  Field_CancelInvisibleFollowerAllPartyMember(0, 30, false, false)
  SetProhibitDigimonRide(false)
  Obj:new(PLAYER, ""):CancelInvisible()
  Motion.Player:ChangeMoveAnimWithBlend("hide", 0, 0)
  PlaySE(210019, 100)
  WaitFrame(5)
  Fade.In(0, 1)
  Motion.Player:ResetMoveAnimationWithBlend(30)
  WaitFrame(20)
end

function Prcs_d1304_EnterElv()
  Field_InvisibleFollowerAllPartyMember(0, 10, false)
  Field_InvisibleFollowerAllPartyMember(INVISIBLE_KEY_FIELD, 0, false)
  Cam.Inst:Set(-43.1, 0.6, -7.8, -35.1, 5.2, -11.5, default, 30)
  WaitFrame(10)
  Motion.Gimmick:Play("change_0002", "e001", false)
  WaitFrame(10)
  PlaySE(200013, 100)
  WaitFrame(20)
  PlayerObjectResetAim()
  ColOff("wall_cl_9001")
  if Guest.IsExist(GST_SIMONS) then
    Fade_OutNoLoadingWithWait(FADE_BLACK, FADE_TIME)
    Obj:new(PLAYER, ""):SetPos(-44.1, 0, -8.5, true)
  else
    Field.AdjustSpeedMovePlayerToTargetFrame2D(-44.1, -8.5, 30)
  end
  if Guest.IsExist(GST_SIMONS) then
    local pc = Obj:new(PLAYER, "")
    local simons = Obj:new(FLD_OBJ_FOLLOWER, GST_SIMONS, "guest")
    local asuka = Obj:new(FLD_OBJ_FOLLOWER, GST_ASUKA_B, "guest")
    local bellstar = Obj:new(FLD_OBJ_FOLLOWER, GST_BEELSTARMON, "guest")
    pc:SetPos(-42.777, 0.106, -8.564, true)
    pc:SetRotationY(90, 0)
    simons:SetPos(-42.757, 0.153, -7.297, true)
    simons:SetRotationY(90, 0)
    asuka:SetPos(-42.754, 0.07, -9.337, true)
    asuka:SetRotationY(90, 0)
    bellstar:SetPos(-44.172, 0.08, -8.55, true)
    bellstar:SetRotationY(90, 0)
    WaitFrame(5)
    FadeAllInWithWait(FADE_BLACK, FADE_TIME)
  end
  WaitFrame(40)
  Motion.Gimmick:Play("change_0002", "e002", false)
  PlaySE(200011, 100)
  Motion.Gimmick:WaitFrame("change_0002", "e002", 0)
  local slot_num = Sound.PlaySE(200012, 100)
  Work.Set(99, slot_num)
  WaitFrame(50)
  MapChange("d", 1301, "start_00", true, 0, 15)
end

function Prcs_d1304_ExitElv()
  if Flg.Check("FLAG_MAIN_08_026", "FLAG_MAIN_08_027") then
    Field_InvisibleFollowerAllPartyMember(0, 0, false)
    local slot_num = Work.Get(99)
    Cam.Inst:Set(-38.08, 1.39, -8.47, -33.93, 2.3, -9.97, default, 0)
    SetFollowerCameraOperateRotation(20, -90)
    local pc = Obj:new(PLAYER, "")
    local heroine = Obj:new(FLD_OBJ_FOLLOWER, GST_HEROINE, "guest")
    local shiroki = Obj:new(FLD_OBJ_FOLLOWER, GST_ASUKA_B, "guest")
    local aegio = Field.GetFollowerIndexForAegiomon()
    pc:SetPos(-44.571, 0, -8.575, true)
    pc:SetRotationY(90, 0)
    heroine:SetPos(-43.702, 0, -7.293, true)
    heroine:SetRotationY(90, 0)
    shiroki:SetPos(-43.02, 0, -8.542, true)
    shiroki:SetRotationY(90, 0)
    Field.ObjectSetPos(FLD_OBJ_FOLLOWER, aegio, -43.748, 0, -9.758)
    Field.ObjectSetRotationY(FLD_OBJ_FOLLOWER, aegio, 90, 0)
    Fade.In(0, Util.SecondFromFrame(30))
    Sound.StopSE(slot_num, 0)
    Motion.Gimmick:Play("change_0002", "e001", false)
    WaitFrame(10)
    PlaySE(200013, 100)
    ColOff("wall_cl_9001")
    WaitFrame(20)
    WaitFrame(40)
    Fade_OutNoLoadingWithWait(FADE_BLACK, FADE_TIME)
    SetFollowerCameraOperateRotation(0, pc.rot_y)
    Motion.Gimmick:Play("change_0002", "e002", false)
    PlaySE(200011, 100)
    Motion.Gimmick:WaitFrame("change_0002", "e002", 0)
    Cam.Inst:Clear(0)
    ColOn("wall_cl_9001")
    Field_CancelInvisibleFollowerAllPartyMember(0, 30, false, true)
    Field_CancelInvisibleFollowerAllGuest(0, 30, false, true)
    pc:SetPos(-36.848, 0, -8.336, true)
    heroine:SetPos(-35.641, 0, -7.13, true)
    shiroki:SetPos(-34.439, 0, -8.467, true)
    Field.ObjectSetPos(FLD_OBJ_FOLLOWER, aegio, -35.181, 0, -9.663)
    WaitFrame(40)
    FadeAllInWithWait(FADE_BLACK, FADE_TIME)
  else
    Field_InvisibleFollowerAllPartyMember(0, 0, false)
    Field_InvisibleFollowerAllGuest(0, 0, false)
    local slot_num = Work.Get(99)
    Field_InvisibleFollowerAllPartyMember(INVISIBLE_KEY_FIELD, 0, false)
    Cam.Inst:Set(-38.08, 1.39, -8.47, -33.93, 2.3, -9.97, default, 0)
    SetFollowerCameraOperateRotation(20, -90)
    Fade.In(0, Util.SecondFromFrame(30))
    Sound.StopSE(slot_num, 0)
    Motion.Gimmick:Play("change_0002", "e001", false)
    WaitFrame(10)
    PlaySE(200013, 100)
    ColOff("wall_cl_9001")
    WaitFrame(20)
    Field.AdjustSpeedMovePlayerToTargetFrame2D(-38, -8.5, 30)
    WaitFrame(40)
    Motion.Gimmick:Play("change_0002", "e002", false)
    PlaySE(200011, 100)
    Motion.Gimmick:WaitFrame("change_0002", "e002", 0)
    local rot = Field.ObjectGetRotationTargetY(PLAYER, 1)
    SetFollowerCameraOperateRotation(0, rot + 90)
    Cam.Inst:Clear(30)
    Field_CancelInvisibleFollowerAllPartyMember(INVISIBLE_KEY_FIELD, 30, false, false)
    ColOn("wall_cl_9001")
    WaitFrame(30)
    Field_CancelInvisibleFollowerAllPartyMember(0, 30, false, true)
    Field_CancelInvisibleFollowerAllGuest(0, 30, false, true)
  end
end
