S040_033 = {
  ID = 33,
  STEP_001 = 1,
  STEP_005 = 5,
  STEP_010 = 10,
  STEP_015 = 15,
  STEP_020 = 20,
  STEP_025 = 25,
  STEP_030 = 30,
  STEP_255 = 255,
  Flg01 = "FLAG_SUB_040_033_001",
  Flg02 = "FLAG_SUB_040_033_002",
  Flg03 = "FLAG_SUB_040_033_003",
  Flg04 = "FLAG_SUB_040_033_004",
  Flg05 = "FLAG_SUB_040_033_005",
  Flg06 = "FLAG_SUB_040_033_006"
}
local text_file = "s040_033"
local base = "s040_033_"
local tlk = Tlk:new(text_file, 1, true)

function S040_033:Event_010()
  if Qst.Sub:Check(self.ID, self.STEP_001, self.STEP_005) then
    local dori_o_index = GetIndex(NPC, "s040_033_001")
    local dori_y_index = GetIndex(NPC, "s040_033_002")
    local dori_o_degree = Field.ObjectGetRotationY(NPC, dori_o_index)
    local dori_y_degree = Field.ObjectGetRotationY(NPC, dori_y_index)
    Field.ObjectLoadMotion(NPC, dori_y_index, "bn01")
    Field.ObjectLoadMotion(NPC, dori_y_index, "bn02")
    Field.ObjectLoadMotion(NPC, dori_y_index, "br01")
    Field.ObjectLoadMotion(NPC, dori_y_index, "fq01")
    Field.ObjectLoadMotion(NPC, dori_y_index, "fq02")
    Field.ObjectLoadMotion(NPC, dori_y_index, "fe02")
    Field.ObjectLoadMotion(NPC, dori_y_index, "fe04")
    Field.ObjectLoadMotion(NPC, dori_o_index, "bn01")
    Field.ObjectLoadMotion(NPC, dori_o_index, "bn02")
    Field.ObjectLoadMotion(NPC, dori_o_index, "br01")
    Field.ObjectLoadMotion(NPC, dori_o_index, "fq01")
    Field.ObjectLoadMotion(NPC, dori_o_index, "fq02")
    Field.ObjectLoadMotion(NPC, dori_o_index, "fe02")
    Field.ObjectLoadMotion(NPC, dori_o_index, "fe04")
    tlk:StartTalkAndCancelDigimonRide()
    HideMinimap(true)
    HideGuide(true)
    Fade_OutNoLoadingWithWait(FADE_BLACK, FADE_TIME)
    Cam.Inst:Set(14.57, 8.68, 107.38, 20.53, 11.23, 114.99, default, 0)
    Obj:new(PLAYER, ""):SetPos(17.22, 8.63, 110.01, true)
    Obj:new(PLAYER, ""):SetRotationY(-60, 0)
    FadeInWithWaitNotFlgCheck(FADE_BLACK, FADE_TIME)
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, dori_y_index, "fq01", 10, 10)
    tlk:Message(base .. "010")
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, dori_o_index, "fq01", 10, 10)
    tlk:Message(base .. "020")
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, dori_y_index, "fe02", 10, 10)
    tlk:Message(base .. "030")
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, dori_o_index, "fe02", 10, 10)
    tlk:Message(base .. "050")
    local result = tlk:Select(3, base .. "060")
    WaitFrame(15)
    if result == RESULT_TALK00 then
      Field.ObjectPlayMotionWithStartMoveMotion(NPC, dori_o_index, "fq01", 10, 10)
      tlk:Message(base .. "070")
    elseif result == RESULT_TALK01 then
      Field.ObjectPlayMotionWithStartMoveMotion(NPC, dori_o_index, "fq01", 10, 10)
      tlk:Message(base .. "080")
    elseif result == RESULT_TALK02 then
      Field.ObjectPlayMotionWithStartMoveMotion(NPC, dori_y_index, "fq01", 10, 10)
      tlk:Message(base .. "090")
      tlk:EndTalk()
      HideMinimap(false)
      HideGuide(false)
      Cam.Inst:Clear(30)
      goto lbl_627
    end
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, dori_y_index, "fe02", 10, 10)
    tlk:Message(base .. "100")
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, dori_o_index, "fq01", 10, 10)
    tlk:Message(base .. "110")
    Field.ObjectSetRotationY(NPC, dori_o_index, -30, 30)
    Field.ObjectPlayMotion(NPC, dori_o_index, "br01", 0, true)
    WaitFrame(30)
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, dori_o_index, "fq01", 10, 10)
    tlk:Message(base .. "120")
    Field.ObjectSetRotationY(NPC, dori_y_index, -90, 30)
    Field.ObjectPlayMotion(NPC, dori_y_index, "br01", 0, true)
    WaitFrame(30)
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, dori_y_index, "fe02", 10, 10)
    tlk:Message(base .. "130")
    Field.ObjectSetRotationY(NPC, dori_o_index, dori_o_degree, 30)
    Field.ObjectPlayMotion(NPC, dori_o_index, "br01", 0, true)
    WaitFrame(30)
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, dori_o_index, "fe02", 10, 10)
    tlk:Message(base .. "140")
    Field.ObjectSetRotationY(NPC, dori_y_index, dori_y_degree, 30)
    Field.ObjectPlayMotion(NPC, dori_y_index, "br01", 0, true)
    WaitFrame(30)
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, dori_y_index, "fq02", 10, 10)
    tlk:Message(base .. "150")
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, dori_o_index, "fq02", 10, 10)
    tlk:Message(base .. "160")
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, dori_o_index, "fq01", 10, 10)
    tlk:Message(base .. "170")
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, dori_y_index, "fe02", 10, 10)
    tlk:Message(base .. "180")
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, dori_y_index, "fq01", 10, 10)
    tlk:Message(base .. "190")
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, dori_o_index, "fe02", 10, 10)
    tlk:Message(base .. "200")
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, dori_o_index, "fq01", 10, 10)
    tlk:Message(base .. "210")
    FadeOutWithWait(0, 15)
    Obj:new(NPC, "s040_033_001"):Invisible()
    FadeInWithWait(0, 15)
    Flg.Set(self.Flg01)
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, dori_y_index, "fq02", 10, 10)
    tlk:Message(base .. "220")
    FadeOutWithWait(0, 15)
    Obj:new(NPC, "s040_033_002"):Invisible()
    FieldObjectSync(FOR_ALL, false)
    FadeInWithWait(0, 15)
    tlk:EndTalk(true)
    Qst.Sub:Start(self.ID, 1, false)
    HideMinimap(false)
    HideGuide(false)
    Qst.Sub:Set(self.ID, self.STEP_005)
    Cam.Inst:Clear(30)
    Field_CancelInvisibleFollowerAllGuest(0, 15, false, false)
    Field_CancelInvisibleFollowerAllPartyMember(0, 15, false, false)
  end
  ::lbl_627::
end

function S040_033:Event_020()
  if Guest.IsExistNum(3) then
    INFO_WINDOW(10050)
    goto lbl_394
  else
    Field.ObjectLoadMotion(PLAYER, 1, "e002")
    Field.ObjectLoadMotion(PLAYER, 1, "e004_01")
    Field.ObjectLoadMotion(PLAYER, 1, "e008")
    Field.ObjectLoadMotion(PLAYER, 1, "e012")
    Field.ObjectLoadMotion(PLAYER, 1, "e013")
    Field.ObjectLoadMotion(PLAYER, 1, "e015")
    Field.ObjectLoadMotion(PLAYER, 1, "e018")
    local dori_y_index = GetIndex(NPC, "s040_033_004")
    Field.ObjectLoadMotion(NPC, dori_y_index, "bn01")
    Field.ObjectLoadMotion(NPC, dori_y_index, "bn02")
    Field.ObjectLoadMotion(NPC, dori_y_index, "br01")
    Field.ObjectLoadMotion(NPC, dori_y_index, "fq01")
    Field.ObjectLoadMotion(NPC, dori_y_index, "fq02")
    Field.ObjectLoadMotion(NPC, dori_y_index, "fe02")
    Field.ObjectLoadMotion(NPC, dori_y_index, "fe04")
    tlk:StartTalkAndCancelDigimonRide()
    HideMinimap(true)
    HideGuide(true)
    Fade_OutNoLoadingWithWait(FADE_BLACK, FADE_TIME)
    Field_InvisibleAllSymbolEnemy(INVISIBLE_KEY_EVENT, 0, false)
    Cam.Inst:Set(3, -6.02, -14.73, 11.45, -3.26, -10.14, default, 0)
    Obj:new(PLAYER, ""):SetPos(7.43, -6.05, -11.4, true)
    Obj:new(PLAYER, ""):SetRotationY(-30, 0)
    Field.ObjectPlayMotion(PLAYER, 1, "e018", 15, true)
    FadeInWithWaitNotFlgCheck(FADE_BLACK, FADE_TIME)
    if not Qst.Sub:Check(self.ID, self.STEP_010) then
      if not Flg.Check(self.Flg02) then
        Field.ObjectPlayMotionWithStartMoveMotion(NPC, dori_y_index, "fq02", 10, 10)
        tlk:Message(base .. "230")
        Field.ObjectPlayMotionWithStartMoveMotion(NPC, dori_y_index, "fq01", 10, 10)
        tlk:Message(base .. "240")
        local result = tlk:Select(2, base .. "250")
        WaitFrame(15)
        if result == RESULT_TALK00 then
          tlk:Message(base .. "260")
        elseif result == RESULT_TALK01 then
          Field.ObjectPlayMotionWithStartMoveMotion(NPC, dori_y_index, "fq02", 10, 10)
          tlk:Message(base .. "270")
          Flg.Set(self.Flg02)
          tlk:EndTalk()
          HideMinimap(false)
          HideGuide(false)
          Cam.Inst:Clear(30)
          Field.ObjectPlayMotion(PLAYER, 1, "fn01_01", 15, true)
          goto lbl_394
        end
      else
        Field.ObjectPlayMotionWithStartMoveMotion(NPC, dori_y_index, "fq01", 10, 10)
        tlk:Message(base .. "280")
        local result = tlk:Select(2, base .. "290")
        WaitFrame(15)
        if result == RESULT_TALK00 then
          tlk:Message(base .. "300")
        elseif result == RESULT_TALK01 then
          Field.ObjectPlayMotionWithStartMoveMotion(NPC, dori_y_index, "fq02", 10, 10)
          tlk:Message(base .. "310")
          tlk:EndTalk()
          HideMinimap(false)
          HideGuide(false)
          Field.ObjectPlayMotion(PLAYER, 1, "fn01_01", 15, true)
          Cam.Inst:Clear(30)
          goto lbl_394
        end
      end
      Field.ObjectPlayMotionWithStartMoveMotion(NPC, dori_y_index, "fq01", 10, 10)
      tlk:Message(base .. "320")
      Qst.Sub:Set(self.ID, self.STEP_010)
      Guest.Add(23733)
      tlk:EndTalk(true)
      EncountFromField_PlaySound(20400330, BTL_MAP_BACCHUS_FOREST1, false)
    elseif not Flg.Check("FLAG_SUB_040_033_005") then
      tlk:EndTalk()
      EncountFromField_PlaySound(20400330, BTL_MAP_BACCHUS_FOREST1, false)
    end
    tlk:EndTalk()
  end
  ::lbl_394::
end

function S040_033:Event_030()
  if Qst.Sub:Check(self.ID, self.STEP_010, self.STEP_015) then
    local dori_y_index = GetIndex(NPC, "s040_033_004")
    Field.ObjectLoadMotion(NPC, dori_y_index, "bn01")
    Field.ObjectLoadMotion(NPC, dori_y_index, "bn02")
    Field.ObjectLoadMotion(NPC, dori_y_index, "fq01")
    Field.ObjectLoadMotion(NPC, dori_y_index, "fq02")
    Field.ObjectLoadMotion(NPC, dori_y_index, "fe02")
    Field.ObjectLoadMotion(NPC, dori_y_index, "fe04")
    if Flg.Check("FLAG_SUB_040_033_005") then
      Obj:new(NPC, "s040_033_003"):Invisible()
      Field.ObjectPlayMotion(PLAYER, 1, "fn01_01", 15, true)
      FadeAllInWithWait(FADE_BLACK, FADE_TIME)
      tlk:StartTalkAndCancelDigimonRide()
      HideMinimap(true)
      HideGuide(true)
      Field.ObjectPlayMotionWithStartMoveMotion(NPC, dori_y_index, "bn02", 10, 10)
      tlk:Message(base .. "330")
      Field.ObjectPlayMotionWithStartMoveMotion(NPC, dori_y_index, "fq02", 10, 10)
      tlk:Message(base .. "340")
      Field.ObjectPlayMotionWithStartMoveMotion(NPC, dori_y_index, "fq01", 10, 10)
      tlk:Message(base .. "350")
      FadeOutWithWait(0, 15)
      Field_CancelInvisibleAllSymbolEnemy(INVISIBLE_KEY_EVENT, 30, false, false)
      Obj:new(NPC, "s040_033_004"):Invisible()
      Flg.Set("FLAG_SUB_040_033_003")
      Flg.Set("FLAG_SUB_040_033_010")
      Flg.Set(self.Flg03)
      Guest.Delete(23733)
      FadeInWithWait(0, 15)
      tlk:EndTalk(true)
      Cam.Inst:Clear(30)
      HideMinimap(false)
      HideGuide(false)
      Qst.Sub:Set(self.ID, self.STEP_015)
      Field_CancelInvisibleFollowerAllGuest(0, 15, false, false)
      Field_CancelInvisibleFollowerAllPartyMember(0, 15, false, false)
    end
  end
end

function S040_033:Event_040()
  if Guest.IsExistNum(3) then
    INFO_WINDOW(10050)
    goto lbl_388
  else
    local dori_o_index = GetIndex(NPC, "s040_033_001")
    Field.ObjectLoadMotion(PLAYER, 1, "e002")
    Field.ObjectLoadMotion(PLAYER, 1, "e004_01")
    Field.ObjectLoadMotion(PLAYER, 1, "e008")
    Field.ObjectLoadMotion(PLAYER, 1, "e012")
    Field.ObjectLoadMotion(PLAYER, 1, "e013")
    Field.ObjectLoadMotion(PLAYER, 1, "e015")
    Field.ObjectLoadMotion(PLAYER, 1, "e018")
    Field.ObjectLoadMotion(NPC, dori_o_index, "bn01")
    Field.ObjectLoadMotion(NPC, dori_o_index, "bn02")
    Field.ObjectLoadMotion(NPC, dori_o_index, "br01")
    Field.ObjectLoadMotion(NPC, dori_o_index, "fq01")
    Field.ObjectLoadMotion(NPC, dori_o_index, "fq02")
    Field.ObjectLoadMotion(NPC, dori_o_index, "fe02")
    Field.ObjectLoadMotion(NPC, dori_o_index, "fe04")
    HideMinimap(true)
    HideGuide(true)
    Fade_OutNoLoadingWithWait(FADE_BLACK, FADE_TIME)
    tlk:StartTalkAndCancelDigimonRide()
    Field_InvisibleAllSymbolEnemy(INVISIBLE_KEY_EVENT, 0, false)
    Cam.Inst:Set(38.72, -29.34, -37.25, 33.65, -27.81, -45.73, default, 0)
    Obj:new(PLAYER, ""):SetPos(36.93, -30.34, -40.36, true)
    Obj:new(PLAYER, ""):SetRotationY(-200, 0)
    Field.ObjectPlayMotion(PLAYER, 1, "e018", 15, true)
    FadeInWithWaitNotFlgCheck(FADE_BLACK, FADE_TIME)
    if not Qst.Sub:Check(self.ID, self.STEP_020) then
      if not Flg.Check(self.Flg04) then
        Field.ObjectPlayMotionWithStartMoveMotion(NPC, dori_o_index, "fq02", 10, 10)
        tlk:Message(base .. "360")
        Field.ObjectPlayMotionWithStartMoveMotion(NPC, dori_o_index, "fq01", 10, 10)
        tlk:Message(base .. "370")
        local result = tlk:Select(2, base .. "380")
        WaitFrame(15)
        if result == RESULT_TALK00 then
          tlk:Message(base .. "390")
        elseif result == RESULT_TALK01 then
          Field.ObjectPlayMotionWithStartMoveMotion(NPC, dori_o_index, "fq02", 10, 10)
          tlk:Message(base .. "400")
          Flg.Set(self.Flg04)
          tlk:EndTalk()
          HideMinimap(false)
          HideGuide(false)
          Field.ObjectPlayMotion(PLAYER, 1, "fn01_01", 15, true)
          Cam.Inst:Clear(30)
          goto lbl_388
        end
      else
        Field.ObjectPlayMotionWithStartMoveMotion(NPC, dori_o_index, "fq01", 10, 10)
        tlk:Message(base .. "410")
        local result = tlk:Select(2, base .. "420")
        WaitFrame(15)
        if result == RESULT_TALK00 then
          tlk:Message(base .. "430")
        elseif result == RESULT_TALK01 then
          Field.ObjectPlayMotionWithStartMoveMotion(NPC, dori_o_index, "fq02", 10, 10)
          tlk:Message(base .. "440")
          tlk:EndTalk()
          HideMinimap(false)
          HideGuide(false)
          Field.ObjectPlayMotion(PLAYER, 1, "fn01_01", 15, true)
          Cam.Inst:Clear(30)
          goto lbl_388
        end
      end
      Field.ObjectPlayMotionWithStartMoveMotion(NPC, dori_o_index, "fe02", 10, 10)
      tlk:Message(base .. "450")
      Qst.Sub:Set(self.ID, self.STEP_020)
      Guest.Add(23732)
      tlk:EndTalk(true)
      EncountFromField_PlaySound(20400331, 10474, false)
    elseif not Flg.Check("FLAG_SUB_040_033_006") then
      EncountFromField_PlaySound(20400331, 10474, false)
    end
  end
  ::lbl_388::
end

function S040_033:Event_050()
  if Qst.Sub:Check(self.ID, self.STEP_020, self.STEP_025) then
    local dori_o_index = GetIndex(NPC, "s040_033_001")
    Field.ObjectLoadMotion(NPC, dori_o_index, "bn01")
    Field.ObjectLoadMotion(NPC, dori_o_index, "bn02")
    Field.ObjectLoadMotion(NPC, dori_o_index, "fq01")
    Field.ObjectLoadMotion(NPC, dori_o_index, "fq02")
    Field.ObjectLoadMotion(NPC, dori_o_index, "fe02")
    Field.ObjectLoadMotion(NPC, dori_o_index, "fe04")
    if Flg.Check("FLAG_SUB_040_033_006") then
      Obj:new(NPC, "s040_033_003"):Invisible()
      Field.ObjectPlayMotion(PLAYER, 1, "fn01_01", 15, true)
      tlk:StartTalkAndCancelDigimonRide()
      HideMinimap(true)
      HideGuide(true)
      WaitFrame(10)
      FadeAllInWithWait(FADE_BLACK, FADE_TIME)
      Field.ObjectPlayMotionWithStartMoveMotion(NPC, dori_o_index, "fe02", 10, 10)
      tlk:Message(base .. "460")
      Field.ObjectPlayMotionWithStartMoveMotion(NPC, dori_o_index, "fq02", 10, 10)
      tlk:Message(base .. "470")
      Field.ObjectPlayMotionWithStartMoveMotion(NPC, dori_o_index, "fq01", 10, 10)
      tlk:Message(base .. "480")
      FadeOutWithWait(0, 15)
      Obj:new(NPC, "s040_033_001"):Invisible()
      Flg.Set(self.Flg05)
      Guest.Delete(23732)
      FadeInWithWait(0, 15)
      tlk:EndTalk(true)
      Cam.Inst:Clear(30)
      HideMinimap(false)
      HideGuide(false)
      Qst.Sub:Set(self.ID, self.STEP_025)
      Field_CancelInvisibleAllSymbolEnemy(INVISIBLE_KEY_EVENT, 30, false, false)
      Field_CancelInvisibleFollowerAllGuest(0, 15, false, false)
      Field_CancelInvisibleFollowerAllPartyMember(0, 15, false, false)
    end
  end
end

function S040_033:Event_060()
  local dori_o_index = GetIndex(NPC, "s040_033_001")
  Field.ObjectLoadMotion(NPC, dori_o_index, "bn01")
  Field.ObjectLoadMotion(NPC, dori_o_index, "bn02")
  Field.ObjectLoadMotion(NPC, dori_o_index, "br01")
  Field.ObjectLoadMotion(NPC, dori_o_index, "fq01")
  Field.ObjectLoadMotion(NPC, dori_o_index, "fq02")
  Field.ObjectLoadMotion(NPC, dori_o_index, "fe02")
  Field.ObjectLoadMotion(NPC, dori_o_index, "fe04")
  local dori_y_index = GetIndex(NPC, "s040_033_002")
  Field.ObjectLoadMotion(NPC, dori_y_index, "bn01")
  Field.ObjectLoadMotion(NPC, dori_y_index, "bn02")
  Field.ObjectLoadMotion(NPC, dori_y_index, "br01")
  Field.ObjectLoadMotion(NPC, dori_y_index, "fq01")
  Field.ObjectLoadMotion(NPC, dori_y_index, "fq02")
  Field.ObjectLoadMotion(NPC, dori_y_index, "fe02")
  Field.ObjectLoadMotion(NPC, dori_y_index, "fe04")
  local dori_o_degree = Field.ObjectGetRotationY(NPC, dori_o_index)
  local dori_y_degree = Field.ObjectGetRotationY(NPC, dori_y_index)
  tlk:StartTalkAndCancelDigimonRide()
  HideMinimap(true)
  HideGuide(true)
  if Qst.Sub:Check(self.ID, self.STEP_025, self.STEP_255) then
    Fade_OutNoLoadingWithWait(FADE_BLACK, FADE_TIME)
    Field_InvisibleAllSymbolEnemy(INVISIBLE_KEY_EVENT, 0, false)
    Cam.Inst:Set(50.87, 72.084, -92.224, 42.26, 73.83, -96.99, default, 0)
    Obj:new(PLAYER, ""):SetPos(46.4, 71.96, -95.63, true)
    Obj:new(PLAYER, ""):SetRotationY(90, 0)
    FadeInWithWaitNotFlgCheck(FADE_BLACK, FADE_TIME)
    PlayerLookAtObject(NPC, "s040_033_002")
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, dori_y_index, "fq02", 10, 10)
    tlk:Message(base .. "490")
    Field.ObjectSetRotationY(NPC, dori_y_index, 320, 30)
    Field.ObjectPlayMotion(NPC, dori_y_index, "br01", 0, true)
    WaitFrame(30)
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, dori_y_index, "fq01", 10, 10)
    tlk:Message(base .. "500")
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, dori_y_index, "fq02", 10, 10)
    tlk:Message(base .. "510")
    tlk:Message(base .. "520")
    FadeOutWithWait(0, 15)
    Obj:new(NPC, "s040_033_001"):CancelInvisible()
    Obj:new(PLAYER, ""):SetRotationY(90, 0)
    PlayerLookAtObject(NPC, "s040_033_001")
    Cam.Inst:Set(50.92, 72.26, -95.27, 41.14, 73.97, -96.5, default, 0)
    Obj:new(PLAYER, ""):SetPos(45.4, 71.96, -95.47, true)
    FadeInWithWait(0, 15)
    Field.ObjectSetRotationY(NPC, dori_y_index, dori_y_degree, 30)
    Field.ObjectPlayMotion(NPC, dori_y_index, "br01", 0, true)
    WaitFrame(30)
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, dori_y_index, "bn01", 10, 10)
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, dori_y_index, "fq01", 10, 10)
    tlk:Message(base .. "530")
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, dori_o_index, "fq01", 10, 10)
    tlk:Message(base .. "540")
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, dori_y_index, "bn02", 10, 10)
    tlk:Message(base .. "550")
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, dori_o_index, "fq01", 10, 10)
    tlk:Message(base .. "560")
    PlayerObjectResetAim()
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, dori_y_index, "fe02", 10, 10)
    tlk:Message(base .. "570")
    FadeOutWithWait(0, 15)
    FadeInWithWait(0, 15)
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, dori_o_index, "fq01", 10, 10)
    tlk:Message(base .. "580")
    tlk:Message(base .. "590")
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, dori_y_index, "fe02", 10, 10)
    tlk:Message(base .. "600")
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, dori_o_index, "fq01", 10, 10)
    tlk:Message(base .. "610")
    tlk:Message(base .. "620")
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, dori_o_index, "fq02", 10, 10)
    tlk:Message(base .. "630")
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, dori_y_index, "fq02", 10, 10)
    tlk:Message(base .. "640")
    tlk:Message(base .. "650")
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, dori_o_index, "fq02", 10, 10)
    tlk:Message(base .. "660")
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, dori_y_index, "fq01", 10, 10)
    tlk:Message(base .. "670")
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, dori_o_index, "fq01", 10, 10)
    tlk:Message(base .. "680")
    tlk:Message(base .. "690")
    tlk:Message(base .. "700")
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, dori_o_index, "fq01", 10, 10)
    tlk:Message(base .. "710")
    tlk:Message(base .. "720")
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, dori_y_index, "fe02", 10, 10)
    tlk:Message(base .. "730")
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, dori_o_index, "fe02", 10, 10)
    tlk:Message(base .. "740")
    tlk:Message(base .. "750")
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, dori_y_index, "fq01", 10, 10)
    tlk:Message(base .. "760")
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, dori_o_index, "bn02", 10, 10)
    tlk:Message(base .. "770")
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, dori_o_index, "fq02", 10, 10)
    tlk:Message(base .. "780")
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, dori_y_index, "fq01", 10, 10)
    tlk:Message(base .. "790")
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, dori_o_index, "fq01", 10, 10)
    tlk:Message(base .. "800")
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, dori_y_index, "fe02", 10, 10)
    tlk:Message(base .. "810")
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, dori_y_index, "fq01", 10, 10)
    tlk:Message(base .. "820")
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, dori_o_index, "fe02", 10, 10)
    tlk:Message(base .. "830")
    Field.ObjectSetRotationY(NPC, dori_o_index, 210, 30)
    Field.ObjectPlayMotion(NPC, dori_o_index, "br01", 0, true)
    WaitFrame(30)
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, dori_o_index, "bn01", 10, 10)
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, dori_o_index, "fq01", 10, 10)
    PlayerLookAtObject(NPC, "s040_033_001")
    tlk:Message(base .. "840")
    Field.ObjectSetRotationY(NPC, dori_y_index, 320, 30)
    Field.ObjectPlayMotion(NPC, dori_y_index, "br01", 0, true)
    WaitFrame(30)
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, dori_y_index, "fq02", 10, 10)
    PlayerLookAtObject(NPC, "s040_033_002")
    tlk:Message(base .. "850")
    PlayerLookAtObject(NPC, "s040_033_001")
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, dori_o_index, "fe02", 10, 10)
    tlk:Message(base .. "860")
    PlayerObjectResetAim()
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, dori_o_index, "fq01", 10, 10)
    tlk:Message(base .. "870")
    tlk:Message(base .. "880")
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, dori_y_index, "fe02", 10, 10)
    tlk:Message(base .. "890")
    Flg.Clear("FLAG_SUB_040_033_010")
    Cam.Inst:Clear(30)
    tlk:EndTalk()
    HideMinimap(false)
    HideGuide(false)
    Qst.Sub:End(self.ID, self.STEP_255)
    Field_CancelInvisibleAllSymbolEnemy(INVISIBLE_KEY_EVENT, 30, false, false)
    goto lbl_905
    PlayerObjectResetAim()
  end
  Field.ObjectPlayMotionWithStartMoveMotion(NPC, dori_o_index, "fq01", 10, 10)
  tlk:Message(base .. "870")
  tlk:Message(base .. "880")
  Field.ObjectPlayMotionWithStartMoveMotion(NPC, dori_y_index, "fe02", 10, 10)
  tlk:Message(base .. "890")
  tlk:EndTalk()
  ::lbl_905::
end

function S040_033:Event_070()
  Obj:new(NPC, "s040_033_001"):Invisible()
end
