S070_057 = {
  ID = 57,
  STEP_001 = 1,
  STEP_005 = 5,
  STEP_255 = 255
}
local base = "s070_057_"
local text_file = "s070_057"

function S070_057:Event_010()
  local minerva_index = GetIndex(NPC, "sub057_001")
  Field.ObjectLoadMotion(NPC, minerva_index, "fn01_01")
  Field.ObjectLoadMotion(NPC, minerva_index, "e002")
  Field.ObjectLoadMotion(NPC, minerva_index, "e003")
  Field.ObjectLoadMotion(NPC, minerva_index, "e004")
  Field.ObjectLoadMotion(NPC, minerva_index, "e008")
  Field.ObjectLoadMotion(NPC, minerva_index, "e012")
  Field.ObjectLoadMotion(NPC, minerva_index, "e013")
  Field.ObjectLoadMotion(NPC, minerva_index, "e018")
  Field.ObjectLoadMotion(NPC, minerva_index, "e513")
  Field.ObjectLoadMotion(PLAYER, 1, "e002")
  Field.ObjectLoadMotion(PLAYER, 1, "e004")
  Field.ObjectLoadMotion(PLAYER, 1, "e004_01")
  Field.ObjectLoadMotion(PLAYER, 1, "e008")
  Field.ObjectLoadMotion(PLAYER, 1, "e010_01")
  Field.ObjectLoadMotion(PLAYER, 1, "e012")
  Field.ObjectLoadMotion(PLAYER, 1, "e013")
  Field.ObjectLoadMotion(PLAYER, 1, "e015")
  Field.ObjectLoadMotion(PLAYER, 1, "e018")
  Field.ObjectLoadMotion(PLAYER, 1, "e019")
  local minerva_index = GetIndex(NPC, "sub057_001")
  Field.ObjectLoadExpression(NPC, minerva_index, "F01_T01")
  if Qst.Sub:Check(self.ID, self.STEP_001, self.STEP_005) then
    local tlk = Tlk:new(text_file, 1, true)
    Fade_OutNoLoadingWithWait(FADE_BLACK, FADE_TIME)
    Obj:new(PLAYER, ""):SetPos(-0.29, 0, -25.01, true)
    Obj:new(PLAYER, ""):SetRotationY(15, 0)
    Cam.Inst:Set(-0.556, -0.1247, -33.7721, 0.249, 1.488, -23.936, default, 0)
    HideMinimap(true)
    HideGuide(true)
    tlk:StartTalkAndCancelDigimonRide()
    WaitFrame(10)
    FadeInWithWaitNotFlgCheck(FADE_BLACK, FADE_TIME)
    Field.ObjectPlayMotion(NPC, minerva_index, "e012", 15, true)
    Field.ObjectChangeExpression(NPC, minerva_index, "F01_T01", EYES_BLINK_TYPE_BLINK, true, 30, AUTO_CANCEL_NONE, 15)
    tlk:Message(base .. "010")
    Field.ObjectChangeExpression(NPC, minerva_index, "F01", EYES_BLINK_TYPE_BLINK, false, 30, AUTO_CANCEL_NONE, 15)
    tlk:MessageClose()
    local result = tlk:Select(3, base .. "020")
    WaitFrame(15)
    Field.ObjectChangeExpression(NPC, minerva_index, "F01_T01", EYES_BLINK_TYPE_BLINK, true, 30, AUTO_CANCEL_NONE, 15)
    if result == RESULT_TALK00 then
      Field.ObjectPlayMotionWithStartMoveMotion(NPC, minerva_index, "e004", 10, 10)
      tlk:Message(base .. "030")
    end
    if result == RESULT_TALK01 then
      Field.ObjectPlayMotionWithStartMoveMotion(NPC, minerva_index, "e002", 10, 10)
      tlk:Message(base .. "040")
    end
    if result == RESULT_TALK02 then
      Field.ObjectPlayMotionWithStartMoveMotion(NPC, minerva_index, "e002", 10, 10)
      tlk:Message(base .. "050")
      tlk:EndTalk()
      Field.ObjectChangeExpression(NPC, minerva_index, "F01", EYES_BLINK_TYPE_BLINK, false, 30, AUTO_CANCEL_NONE, 15)
    else
      Field.ObjectPlayMotion(NPC, minerva_index, "e008", 15, true)
      tlk:Message(base .. "060")
      tlk:Message(base .. "070")
      Field.ObjectPlayMotion(NPC, minerva_index, "e018", 15, true)
      tlk:Message(base .. "080")
      tlk:Message(base .. "090")
      Field.ObjectChangeExpression(NPC, minerva_index, "F01", EYES_BLINK_TYPE_BLINK, false, 30, AUTO_CANCEL_NONE, 15)
      tlk:EndTalk(true)
      Qst.Sub:Start(self.ID, 1, false)
      Qst.Sub:Set(self.ID, self.STEP_005)
      Flg.Set("FLAG_SUB_070_057_001")
      EncountFromField_PlaySound(20700570, 11272, false)
    end
    Cam.Inst:Clear(30)
  end
end

function S070_057:Event_020()
  if Qst.Sub:Check(self.ID, self.STEP_005, self.STEP_255) and Flg.Check("FLAG_SUB_070_057_002") then
    local minerva_index = GetIndex(NPC, "sub057_001")
    Field.ObjectLoadMotion(NPC, minerva_index, "fn01_01")
    Field.ObjectLoadMotion(NPC, minerva_index, "e002")
    Field.ObjectLoadMotion(NPC, minerva_index, "e003")
    Field.ObjectLoadMotion(NPC, minerva_index, "e004")
    Field.ObjectLoadMotion(NPC, minerva_index, "e008")
    Field.ObjectLoadMotion(NPC, minerva_index, "e012")
    Field.ObjectLoadMotion(NPC, minerva_index, "e013")
    Field.ObjectLoadMotion(NPC, minerva_index, "e014")
    Field.ObjectLoadMotion(NPC, minerva_index, "e018")
    Field.ObjectLoadMotion(NPC, minerva_index, "e513")
    Field.ObjectLoadMotion(PLAYER, 1, "e002")
    Field.ObjectLoadMotion(PLAYER, 1, "e004")
    Field.ObjectLoadMotion(PLAYER, 1, "e004_01")
    Field.ObjectLoadMotion(PLAYER, 1, "e008")
    Field.ObjectLoadMotion(PLAYER, 1, "e010_01")
    Field.ObjectLoadMotion(PLAYER, 1, "e012")
    Field.ObjectLoadMotion(PLAYER, 1, "e013")
    Field.ObjectLoadMotion(PLAYER, 1, "e015")
    Field.ObjectLoadMotion(PLAYER, 1, "e018")
    Field.ObjectLoadMotion(PLAYER, 1, "e019")
    local minerva_index = GetIndex(NPC, "sub057_001")
    Field.ObjectLoadExpression(NPC, minerva_index, "F01_T01")
    local tlk = Tlk:new(text_file, 1, true)
    Cam.Inst:Set(-0.556, -0.1247, -33.7721, 0.249, 1.488, -23.936, default, 0)
    WaitFrame(15)
    HideMinimap(true)
    HideGuide(true)
    tlk:StartTalkAndCancelDigimonRide()
    FadeAllInWithWait(FADE_BLACK, FADE_TIME)
    Field.ObjectChangeExpression(NPC, minerva_index, "F01_T01", EYES_BLINK_TYPE_BLINK, true, 30, AUTO_CANCEL_NONE, 15)
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, minerva_index, "e002", 10, 10)
    tlk:Message(base .. "130")
    Field.ObjectPlayMotion(NPC, minerva_index, "e012", 15, true)
    tlk:Message(base .. "140")
    tlk:Message(base .. "150")
    Field.ObjectPlayMotion(NPC, minerva_index, "e002", 15, true)
    tlk:Message(base .. "160")
    Field.ObjectPlayMotion(NPC, minerva_index, "e018", 15, true)
    tlk:Message(base .. "170")
    Field.ObjectChangeExpression(NPC, minerva_index, "F01", EYES_BLINK_TYPE_BLINK, false, 30, AUTO_CANCEL_NONE, 15)
    PlaySE(404005, 100)
    Fade_OutNoLoadingWithWait(FADE_WHITE, FADE_TIME)
    WaitFrame(5)
    WaitFrame(10)
    FadeInWithWaitNotFlgCheck(FADE_WHITE, FADE_TIME)
    Field.ObjectChangeExpression(NPC, minerva_index, "F01_T01", EYES_BLINK_TYPE_BLINK, true, 30, AUTO_CANCEL_NONE, 15)
    Field.ObjectPlayMotion(NPC, minerva_index, "e008", 15, true)
    tlk:Message(base .. "180")
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, minerva_index, "e002", 10, 10)
    tlk:Message(base .. "190")
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, minerva_index, "e012", 10, 10)
    tlk:Message(base .. "200")
    Field.ObjectChangeExpression(NPC, minerva_index, "F01", EYES_BLINK_TYPE_BLINK, false, 30, AUTO_CANCEL_NONE, 15)
    tlk:EndTalk(true)
    WaitFrame(30)
    Flg.Set("FLAG_IS_CLEAR_S070_057")
    Fade_OutNoLoadingWithWait(FADE_BLACK, FADE_TIME)
    FieldObjectSync(FOR_ALL, false)
    WaitFrame(30)
    FadeInWithWaitNotFlgCheck(FADE_BLACK, FADE_TIME)
    HideMinimap(false)
    HideGuide(false)
    Qst.Sub:End(self.ID, self.STEP_255)
    Cam.Inst:Clear(30)
    Field_CancelInvisibleFollowerAllGuest(0, 15, false, false)
    Field_CancelInvisibleFollowerAllPartyMember(0, 15, false, false)
  end
end
