S110_102 = {
  ID = 102,
  STEP_001 = 1,
  STEP_005 = 5,
  STEP_010 = 10,
  STEP_015 = 15,
  STEP_255 = 255,
  Flg01 = "FLAG_SUB_110_102_001",
  Flg02 = "FLAG_SUB_110_102_002",
  Flg03 = "FLAG_SUB_110_102_003",
  Flg04 = "FLAG_SUB_110_102_004",
  Flg05 = "FLAG_SUB_110_102_005"
}
local text_file = "s110_102"
local base = "s110_102_"

function S110_102:Event_010()
  if Qst.Main:IsCompleted(M360.ID) and Qst.Sub:IsAllCompleted({19, 100}) and Flg.Check("FLAG_SUB_100_087_015") and not Qst.Sub:IsCompleted(self.ID) then
    if Guest.IsExistNum(3) then
      INFO_WINDOW(10050)
      return
    end
    if not Qst.Sub:Check(self.ID, self.STEP_005) then
      Flg.Set(self.Flg03)
      HideMinimap(true)
      HideGuide(true)
      local arufos_index = GetIndex(NPC, "s110_102_001")
      Field.ObjectLoadMotion(NPC, arufos_index, "bn01")
      Field.ObjectLoadMotion(NPC, arufos_index, "fq01")
      Field.ObjectLoadMotion(NPC, arufos_index, "fq02")
      Field.ObjectLoadMotion(NPC, arufos_index, "fe02")
      Field.ObjectLoadMotion(NPC, arufos_index, "fe03")
      Field.ObjectLoadMotion(NPC, arufos_index, "fe04")
      Fade_OutNoLoadingWithWait(FADE_BLACK, FADE_TIME)
      Cam.Inst:Set(45.1, 3.42, -21.83, 52.61, 0.085, -16.13, default, 0)
      Obj:new(PLAYER, ""):SetPos(48.837, -0.182, -18.28, true)
      Obj:new(PLAYER, ""):SetRotationY(330, 0)
      local tlk = Tlk:new(text_file, 1, true)
      tlk:StartTalkAndCancelDigimonRide()
      WaitFrame(10)
      FadeAllInWithWait(FADE_BLACK, FADE_TIME)
      Field.ObjectLookAtTheObject(PLAYER, 1, NPC, arufos_index, 15, 10)
      WaitFrame(15)
      Field.ObjectPlayMotion(NPC, arufos_index, "fq02", 10, true)
      tlk:Message(base .. "010")
      Field.ObjectPlayMotion(NPC, arufos_index, "fq01", 10, true)
      tlk:Message(base .. "020")
      Field.ObjectPlayMotion(NPC, arufos_index, "fq02", 10, true)
      tlk:Message(base .. "030")
      Field.ObjectPlayMotion(NPC, arufos_index, "bn01", 10, true)
      local result = tlk:Select(3, base .. "040")
      WaitFrame(30)
      if result == RESULT_TALK00 then
        Field.ObjectPlayMotionWithStartMoveMotion(NPC, arufos_index, "fe02", 10, 10)
        tlk:Message(base .. "050")
      elseif result == RESULT_TALK01 then
        Field.ObjectPlayMotionWithStartMoveMotion(NPC, arufos_index, "fe03", 10, 10)
        tlk:Message(base .. "060")
      elseif result == RESULT_TALK02 then
        Field.ObjectPlayMotion(NPC, arufos_index, "fq01", 10, true)
        tlk:Message(base .. "070")
        Field.ObjectPlayMotion(NPC, arufos_index, "bn01", 10, true)
        tlk:EndTalk()
        goto lbl_359
      end
      Field.ObjectPlayMotion(NPC, arufos_index, "fq01", 10, true)
      tlk:Message(base .. "080")
      Field.ObjectPlayMotionWithStartMoveMotion(NPC, arufos_index, "fe04", 10, 10)
      tlk:Message(base .. "090")
      tlk:MessageClose()
      Talk.CloseLetterBox()
      Qst.Sub:Start(self.ID, 1, false)
      HideMinimap(false)
      HideGuide(false)
      Qst.Sub:Set(self.ID, self.STEP_005)
      Fade_OutNoLoadingWithWait(FADE_BLACK, FADE_TIME)
      Talk.OpenLetterBox()
      tlk:EndTalk()
      WaitFrame(1)
      Flg.Set("FLAG_SKIP_AREACHANGE_MOVE")
      Cam.Inst:Clear(0)
      MapChange("d", 305, "start_01", false, FADE_BLACK, FADE_TIME)
      ::lbl_359::
      Cam.Inst:Clear(30)
      WaitFrame(15)
    end
  end
end

function S110_102:Event_020()
  if Qst.Sub:Check(self.ID, self.STEP_005, self.STEP_010) and not Flg.Check(self.Flg02) and not Flg.Check(self.Flg01) then
    HideMinimap(true)
    HideGuide(true)
    local arufos_index = GetIndex(NPC, "s110_102_001")
    local game_index = GetIndex(NPC, "S020_019_game_01")
    local nepu_index = GetIndex(NPC, "npc_0001")
    Field.ObjectLoadMotion(NPC, arufos_index, "bn01")
    Field.ObjectLoadMotion(NPC, arufos_index, "fq01")
    Field.ObjectLoadMotion(NPC, arufos_index, "fq02")
    Field.ObjectLoadMotion(NPC, arufos_index, "fe02")
    Field.ObjectLoadMotion(NPC, arufos_index, "fe03")
    Field.ObjectLoadMotion(NPC, arufos_index, "fe04")
    Field.ObjectLoadMotion(NPC, game_index, "bn01")
    Field.ObjectLoadMotion(NPC, game_index, "fq01")
    Field.ObjectLoadMotion(NPC, game_index, "fq02")
    Field.ObjectLoadMotion(NPC, game_index, "fe02")
    Field.ObjectLoadMotion(NPC, nepu_index, "e100")
    Field.ObjectLoadMotion(NPC, nepu_index, "e101")
    Field.ObjectLoadMotion(NPC, nepu_index, "e104")
    Field.ObjectLoadMotion(NPC, nepu_index, "e107")
    Field.ObjectLoadMotion(NPC, nepu_index, "e108")
    Field.ObjectLoadMotion(PLAYER, 1, "fn01_01")
    Field.ObjectLoadMotion(PLAYER, 1, "bc01")
    Field.ObjectLoadMotion(PLAYER, 1, "bn01")
    Field.ObjectLoadMotion(PLAYER, 1, "e002")
    Field.ObjectLoadMotionBlend(PLAYER, 1, "blend01")
    local tlk = Tlk:new(text_file, 1, true)
    Flg.Set(self.Flg01)
    Cam.Inst:Set(0.504, 39.94, -109.111, 0.826, 37.394, -99.446, default, 0)
    tlk:StartTalkAndCancelDigimonRide()
    WaitFrame(15)
    HideMinimap(true)
    WaitFrame(5)
    HideGuide(true)
    WaitFrame(5)
    FadeAllInWithWait(FADE_BLACK, FADE_TIME)
    Field.ObjectLookAtTheObject(PLAYER, 1, NPC, nepu_index, 15, 10)
    Field.ObjectLookAtTheObject(NPC, arufos_index, NPC, nepu_index, 15, 10)
    WaitFrame(30)
    Field.ObjectPlayMotion(NPC, nepu_index, "e101", 10, true)
    tlk:Message(base .. "110")
    Field.ObjectPlayMotion(NPC, nepu_index, "e100", 10, true)
    Field.ObjectPlayMotion(NPC, arufos_index, "fq02", 10, true)
    tlk:Message(base .. "120")
    tlk:MessageClose()
    Fade_OutNoLoadingWithWait(FADE_BLACK, FADE_TIME)
    Field.ObjectPlayMotion(NPC, arufos_index, "bn01", 10, true)
    WaitFrame(30)
    FadeAllInWithWait(FADE_BLACK, FADE_TIME)
    Field.ObjectPlayMotion(NPC, nepu_index, "e108", 10, true)
    tlk:Message(base .. "130")
    Field.ObjectPlayMotion(NPC, nepu_index, "e101", 10, true)
    tlk:Message(base .. "140")
    Field.ObjectPlayMotion(NPC, nepu_index, "e100", 10, true)
    Field.ObjectPlayMotion(NPC, arufos_index, "fq01", 10, true)
    tlk:Message(base .. "150")
    Field.ObjectPlayMotion(NPC, arufos_index, "bn01", 10, true)
    Field.ObjectPlayMotion(NPC, nepu_index, "e101", 10, true)
    tlk:Message(base .. "160")
    tlk:Message(base .. "170")
    tlk:MessageClose()
    Field.ObjectPlayMotion(NPC, nepu_index, "e100", 10, true)
    Field.ObjectLookAtTheObject(PLAYER, 1, NPC, game_index, 15, 10)
    Field.ObjectLookAtTheObject(NPC, arufos_index, NPC, game_index, 15, 10)
    WaitFrame(15)
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, game_index, "fe02", 10, 10)
    tlk:Message(base .. "180")
    tlk:MessageClose()
    WaitFrame(15)
    Field.ObjectLookAtTheObject(PLAYER, 1, NPC, nepu_index, 15, 10)
    Field.ObjectLookAtTheObject(NPC, arufos_index, NPC, nepu_index, 15, 10)
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, arufos_index, "fe04", 10, 10)
    tlk:Message(base .. "190")
    tlk:MessageClose()
    WaitFrame(30)
    Field.ObjectPlayMotion(NPC, nepu_index, "e108", 10, true)
    tlk:Message(base .. "200")
    Field.ObjectPlayMotion(NPC, nepu_index, "e101", 10, true)
    tlk:Message(base .. "210")
    tlk:Message(base .. "220")
    Field.ObjectPlayMotion(NPC, nepu_index, "e100", 10, true)
    tlk:MessageClose()
    WaitFrame(30)
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, arufos_index, "fe03", 10, 10)
    tlk:Message(base .. "230")
    Field.ObjectPlayMotion(NPC, nepu_index, "e101", 10, true)
    tlk:Message(base .. "240")
    tlk:Message(base .. "250")
    Field.ObjectPlayMotion(NPC, nepu_index, "e100", 10, true)
    Field.ObjectPlayMotion(NPC, arufos_index, "fq02", 10, true)
    tlk:Message(base .. "260")
    Field.ObjectPlayMotion(NPC, arufos_index, "bn01", 10, true)
    Field.ObjectPlayMotion(NPC, nepu_index, "e101", 10, true)
    tlk:Message(base .. "270")
    Field.ObjectPlayMotion(NPC, nepu_index, "e108", 10, true)
    tlk:Message(base .. "280")
    Field.ObjectPlayMotion(NPC, nepu_index, "e104", 10, true)
    tlk:Message(base .. "290")
    Field.ObjectPlayMotion(NPC, nepu_index, "e100", 10, true)
    Field.ObjectPlayMotion(NPC, arufos_index, "fq02", 10, true)
    tlk:Message(base .. "300")
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, arufos_index, "fe02", 10, 10)
    tlk:Message(base .. "310")
    Field.ObjectLookAt(PLAYER, 1, 4.808, 40, -111.241, 15, 10)
    local result = tlk:Select(3, base .. "320")
    WaitFrame(30)
    if result == RESULT_TALK00 then
      Field.ObjectPlayMotion(NPC, arufos_index, "fq02", 10, true)
      tlk:Message(base .. "330")
    elseif result == RESULT_TALK01 then
      Field.ObjectPlayMotion(NPC, arufos_index, "fq01", 10, true)
      tlk:Message(base .. "340")
    elseif result == RESULT_TALK02 then
      Field.ObjectPlayMotion(NPC, arufos_index, "fq02", 10, true)
      tlk:Message(base .. "350")
    end
    tlk:MessageClose()
    Field.ObjectPlayMotion(NPC, arufos_index, "bn01", 10, true)
    WaitFrame(30)
    Field.ObjectPlayMotion(NPC, arufos_index, "fq01", 10, true)
    tlk:Message(base .. "360")
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, arufos_index, "fe04", 10, 10)
    tlk:Message(base .. "370")
    Field.ObjectLookAtTheObject(PLAYER, 1, NPC, nepu_index, 15, 10)
    Field.ObjectPlayMotion(NPC, nepu_index, "e104", 10, true)
    tlk:Message(base .. "380")
    Field.ObjectPlayMotion(NPC, nepu_index, "e100", 10, true)
    result = tlk:Select(2, base .. "390")
    WaitFrame(30)
    if result == RESULT_TALK00 then
      Field.ObjectPlayMotion(NPC, nepu_index, "e104", 10, true)
      Qst.Sub:Set(self.ID, self.STEP_010)
      tlk:Message(base .. "400")
      tlk:MessageClose()
      Field.ObjectPlayMotion(NPC, nepu_index, "e107", 10, true)
      Field.ObjectPlayMotionWithStartMoveMotion(NPC, arufos_index, "fe04", 10, 10)
      Field.ObjectPlayMotionWithStartMoveMotion(PLAYER, 1, "bc01", 10, 10)
      WaitFrame(30)
      tlk:EndTalk(true)
      EncountFromField_PlaySound(21101020, 10375, false)
    elseif result == RESULT_TALK01 then
      Field.ObjectPlayMotion(NPC, nepu_index, "e108", 10, true)
      tlk:Message(base .. "410")
      Field.ObjectPlayMotion(NPC, nepu_index, "e100", 10, true)
      tlk:EndTalk()
      HideMinimap(false)
      HideGuide(false)
      Qst.Sub:Set(self.ID, self.STEP_010)
      Cam.Inst:Clear(30)
      WaitFrame(15)
    end
  end
end

function S110_102:Event_025()
  if Qst.Sub:Check(self.ID, self.STEP_010, self.STEP_015) and Flg.Check(self.Flg01, self.Flg02) then
    HideMinimap(true)
    HideGuide(true)
    local arufos_index = GetIndex(NPC, "s110_102_001")
    local nepu_index = GetIndex(NPC, "npc_0001")
    Field.ObjectLoadMotion(NPC, arufos_index, "bn01")
    Field.ObjectLoadMotion(NPC, arufos_index, "fe04")
    local nepu_index = GetIndex(NPC, "npc_0001")
    Field.ObjectLoadMotion(NPC, nepu_index, "e100")
    Field.ObjectLoadMotion(NPC, nepu_index, "e101")
    Field.ObjectLoadMotion(NPC, nepu_index, "e104")
    Field.ObjectLoadMotion(NPC, nepu_index, "e107")
    Field.ObjectLoadMotion(NPC, nepu_index, "e108")
    Field.ObjectLoadMotion(PLAYER, 1, "fn01_01")
    Field.ObjectLoadMotion(PLAYER, 1, "bc01")
    Field.ObjectLoadMotion(PLAYER, 1, "bn01")
    Field.ObjectLoadMotion(PLAYER, 1, "e002")
    Field.ObjectLoadMotionBlend(PLAYER, 1, "blend01")
    Fade_OutNoLoadingWithWait(FADE_BLACK, FADE_TIME)
    Obj:new(PLAYER, ""):SetPos(0.039, 36.858, -110.148, true)
    Obj:new(PLAYER, ""):SetRotationY(0, 0)
    local tlk = Tlk:new(text_file, 1, true)
    Cam.Inst:Set(0.504, 39.94, -109.111, 0.826, 37.394, -99.446, default, 30)
    tlk:StartTalkAndCancelDigimonRide()
    WaitFrame(10)
    FadeAllInWithWait(FADE_BLACK, FADE_TIME)
    WaitFrame(10)
    Field.ObjectLookAtTheObject(PLAYER, 1, NPC, nepu_index, 15, 10)
    Field.ObjectPlayMotion(NPC, nepu_index, "e101", 10, true)
    tlk:Message(base .. "420")
    Field.ObjectPlayMotion(NPC, nepu_index, "e100", 10, true)
    local result = tlk:Select(2, base .. "430")
    WaitFrame(30)
    if result == RESULT_TALK00 then
      Field.ObjectPlayMotion(NPC, nepu_index, "e104", 10, true)
      tlk:Message(base .. "440")
      tlk:MessageClose()
      Field.ObjectPlayMotion(NPC, nepu_index, "e107", 10, true)
      Field.ObjectPlayMotionWithStartMoveMotion(NPC, arufos_index, "fe04", 10, 10)
      Field.ObjectPlayMotionWithStartMoveMotion(PLAYER, 1, "bc01", 10, 10)
      WaitFrame(30)
      tlk:EndTalk(true)
      EncountFromField_PlaySound(21101020, 10375, false)
    elseif result == RESULT_TALK01 then
      Field.ObjectPlayMotion(NPC, nepu_index, "e108", 10, true)
      tlk:Message(base .. "450")
      Field.ObjectPlayMotion(NPC, nepu_index, "e100", 10, true)
      tlk:EndTalk()
      HideMinimap(false)
      HideGuide(false)
      Cam.Inst:Clear(30)
      WaitFrame(15)
    end
  end
end

function S110_102:Event_030()
  if Qst.Sub:Check(self.ID, self.STEP_010, self.STEP_015) then
    local game_index = GetIndex(NPC, "S020_019_game_01")
    Field.ObjectLoadMotion(NPC, game_index, "bn01")
    Field.ObjectLoadMotion(NPC, game_index, "fq01")
    Field.ObjectLoadMotion(NPC, game_index, "fq02")
    Field.ObjectLoadMotion(NPC, game_index, "fe02")
    local tlk = Tlk:new(text_file, 1, true)
    tlk:StartTalkAndCancelDigimonRide()
    Field.ObjectLookAtTheObject(PLAYER, 1, NPC, game_index, 15, 10)
    Cam.Inst:Set(-7.922, 40.919, -112.723, -2.425, 39.388, -104.511, default, 30)
    WaitFrame(45)
    Field.ObjectPlayMotion(NPC, game_index, "fq01", 10, true)
    tlk:Message(base .. "460")
    Field.ObjectPlayMotion(NPC, game_index, "bn01", 10, true)
    tlk:EndTalk()
    Cam.Inst:Clear(30)
    WaitFrame(15)
  elseif Qst.Sub:Check(self.ID, self.STEP_015, self.STEP_255) then
    local game_index = GetIndex(NPC, "s110_102_002")
    Field.ObjectLoadMotion(NPC, game_index, "bn01")
    Field.ObjectLoadMotion(NPC, game_index, "fq01")
    Field.ObjectLoadMotion(NPC, game_index, "fq02")
    Field.ObjectLoadMotion(NPC, game_index, "fe02")
    local tlk = Tlk:new(text_file, 1, true)
    tlk:StartTalkAndCancelDigimonRide()
    Field.ObjectLookAtTheObject(PLAYER, 1, NPC, game_index, 15, 10)
    Cam.Inst:Set(-107, -8.746, 86.81, -106.47, -12.278, 77.47, default, 30)
    WaitFrame(45)
    Field.ObjectPlayMotion(NPC, game_index, "fq01", 10, true)
    tlk:Message(base .. "600")
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, game_index, "fe02", 10, 10)
    tlk:Message(base .. "610")
    Field.ObjectPlayMotion(NPC, game_index, "bn01", 10, true)
    tlk:EndTalk()
    Cam.Inst:Clear(30)
    WaitFrame(15)
  end
end

function S110_102:Event_040()
  if Qst.Sub:Check(self.ID, self.STEP_010, self.STEP_015) and Flg.Check(self.Flg02, self.Flg04) then
    HideMinimap(true)
    HideGuide(true)
    Digimon.RestoreAllParty()
    local arufos_index = GetIndex(NPC, "s110_102_001")
    local game_index = GetIndex(NPC, "S020_019_game_01")
    local nepu_index = GetIndex(NPC, "npc_0001")
    Field.ObjectLoadMotion(NPC, arufos_index, "bn01")
    Field.ObjectLoadMotion(NPC, arufos_index, "fq01")
    Field.ObjectLoadMotion(NPC, arufos_index, "fq02")
    Field.ObjectLoadMotion(NPC, arufos_index, "fe02")
    Field.ObjectLoadMotion(NPC, arufos_index, "fe03")
    Field.ObjectLoadMotion(NPC, arufos_index, "fe04")
    Field.ObjectLoadMotion(NPC, game_index, "bn01")
    Field.ObjectLoadMotion(NPC, game_index, "fq01")
    Field.ObjectLoadMotion(NPC, game_index, "fq02")
    Field.ObjectLoadMotion(NPC, game_index, "fe02")
    Field.ObjectLoadMotion(NPC, nepu_index, "e100")
    Field.ObjectLoadMotion(NPC, nepu_index, "e101")
    Field.ObjectLoadMotion(NPC, nepu_index, "e104")
    Field.ObjectLoadMotion(NPC, nepu_index, "e107")
    Field.ObjectLoadMotion(NPC, nepu_index, "e108")
    Field.ObjectLoadMotion(PLAYER, 1, "fn01_01")
    Field.ObjectLoadMotion(PLAYER, 1, "bc01")
    Field.ObjectLoadMotion(PLAYER, 1, "bn01")
    Field.ObjectLoadMotion(PLAYER, 1, "e002")
    Field.ObjectLoadMotionBlend(PLAYER, 1, "blend01")
    Field.ObjectPlayMotion(PLAYER, 1, "bn01", 0, true)
    Field.ObjectPlayMotion(NPC, nepu_index, "e100", 0, true)
    Field.ObjectLookAtTheObject(PLAYER, 1, NPC, nepu_index, 15, 10)
    local tlk = Tlk:new(text_file, 1, true)
    tlk:StartTalkAndCancelDigimonRide()
    WaitFrame(10)
    FadeAllInWithWait(FADE_BLACK, FADE_TIME)
    WaitFrame(15)
    Field.ObjectPlayMotion(NPC, nepu_index, "e107", 10, true)
    tlk:Message(base .. "470")
    Field.ObjectPlayMotion(PLAYER, 1, "fn01_01", 15, true)
    Field.ObjectPlayMotion(NPC, nepu_index, "e104", 10, true)
    tlk:Message(base .. "480")
    Field.ObjectPlayMotion(NPC, nepu_index, "e101", 10, true)
    tlk:Message(base .. "490")
    Field.ObjectPlayMotion(NPC, nepu_index, "e100", 10, true)
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, arufos_index, "fe03", 10, 10)
    tlk:Message(base .. "500")
    Field.ObjectPlayMotion(NPC, nepu_index, "e101", 10, true)
    tlk:Message(base .. "510")
    Field.ObjectPlayMotion(NPC, nepu_index, "e100", 10, true)
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, game_index, "fe02", 10, 10)
    tlk:Message(base .. "520")
    Field.ObjectPlayMotion(NPC, game_index, "fq01", 10, true)
    tlk:Message(base .. "530")
    tlk:MessageClose()
    Flg.Set(self.Flg05)
    Fade_OutNoLoadingWithWait(FADE_BLACK, FADE_TIME)
    FieldObjectSync(NPC, false)
    Cam.Inst:Set(2.9, 40.36, -110.94, -1.064, 36.966, -102.41, default, 0)
    WaitFrame(30)
    FadeAllInWithWait(FADE_BLACK, FADE_TIME)
    WaitFrame(15)
    Field.ObjectLookAt(PLAYER, 1, 4.808, 40, -111.241, 15, 10)
    Field.ObjectPlayMotion(NPC, arufos_index, "fq01", 10, true)
    tlk:Message(base .. "540")
    Field.ObjectPlayMotion(NPC, arufos_index, "bn01", 10, true)
    Field.ObjectLookAtTheObject(PLAYER, 1, NPC, nepu_index, 15, 10)
    Field.ObjectPlayMotion(NPC, nepu_index, "e101", 10, true)
    tlk:Message(base .. "550")
    Field.ObjectPlayMotion(NPC, nepu_index, "e108", 10, true)
    tlk:Message(base .. "560")
    Field.ObjectPlayMotion(NPC, nepu_index, "e101", 10, true)
    tlk:Message(base .. "570")
    Field.ObjectPlayMotion(NPC, nepu_index, "e100", 10, true)
    Field.ObjectPlayMotion(NPC, arufos_index, "fq01", 10, true)
    tlk:Message(base .. "580")
    Field.ObjectPlayMotion(NPC, arufos_index, "bn01", 10, true)
    Field.ObjectPlayMotion(NPC, nepu_index, "e101", 10, true)
    tlk:Message(base .. "590")
    Field.ObjectPlayMotion(NPC, nepu_index, "e100", 10, true)
    tlk:MessageClose()
    Fade_OutNoLoadingWithWait(FADE_BLACK, FADE_TIME)
    tlk:EndTalk()
    Flg.Set(self.Flg04)
    Qst.Sub:Set(self.ID, self.STEP_015)
    FieldObjectSync(NPC, true)
    Cam.Inst:Clear(0)
    MapChange("d", 501, "start_09", false, FADE_BLACK, FADE_TIME)
  end
end

function S110_102:Event_050()
  if Qst.Sub:Check(self.ID, self.STEP_015, self.STEP_255) then
    HideMinimap(true)
    HideGuide(true)
    local arufos_index = GetIndex(NPC, "s110_102_001")
    Field.ObjectLoadMotion(NPC, arufos_index, "bn01")
    Field.ObjectLoadMotion(NPC, arufos_index, "fq01")
    Field.ObjectLoadMotion(NPC, arufos_index, "fq02")
    Field.ObjectLoadMotion(NPC, arufos_index, "fe02")
    Field.ObjectLoadMotion(NPC, arufos_index, "fe03")
    Field.ObjectLoadMotion(NPC, arufos_index, "fe04")
    local tlk = Tlk:new(text_file, 1, true)
    Fade_OutNoLoadingWithWait(FADE_BLACK, FADE_TIME)
    Field.ObjectResetAim(NPC, arufos_index, 0)
    Cam.Inst:Set(-102.7, -9.064, 85.3, -101.78, -12.05, 75.804, default, 0)
    Obj:new(PLAYER, ""):SetPos(-103, -12.3, 82, true)
    Obj:new(PLAYER, ""):SetRotationYToObject(NPC, "s110_102_001", 0)
    Obj:new(NPC, "s110_102_001"):SetRotationYToObject(PLAYER, "", 0)
    Obj:new(NPC, "s110_102_002"):Invisible()
    Field.ObjectLookAtTheObject(PLAYER, 1, NPC, arufos_index, 15, 10)
    tlk:StartTalkAndCancelDigimonRide()
    WaitFrame(10)
    Field.SetMobTransparentFrontOfCamera(0, 10, 10, 10)
    FadeAllInWithWait(FADE_BLACK, FADE_TIME)
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, arufos_index, "fe02", 10, 10)
    tlk:Message(base .. "640")
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, arufos_index, "fq02", 10, 10)
    tlk:Message(base .. "650")
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, arufos_index, "fe04", 10, 10)
    tlk:Message(base .. "660")
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, arufos_index, "fq01", 10, 10)
    tlk:Message(base .. "670")
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, arufos_index, "fe03", 10, 10)
    tlk:Message(base .. "680")
    Field.ObjectPlayMotionWithStartMoveMotion(NPC, arufos_index, "fe04", 10, 10)
    tlk:Message(base .. "690")
    tlk:EndTalk()
    require("S100_087")
    Flg.Set(S100_087.Flgs.Flg06)
    S100_087.AddReturnRoyalKnightsNum()
    S100_087:Event_020()
    Fade_OutNoLoadingWithWait(FADE_BLACK, FADE_TIME)
    Field.ClearMobTransparentFrontOfCamera(0)
    Flg.Set("FLAG_IS_CLEAR_S110_102")
    FieldObjectSync(NPC, false)
    Cam.Inst:Clear(0)
    WaitFrame(30)
    FadeAllInWithWait(FADE_BLACK, FADE_TIME)
    WaitFrame(15)
    HideMinimap(false)
    HideGuide(false)
    Qst.Sub:End(self.ID, self.STEP_255)
  end
end
